### ISSUE TITLE
Unable to remove net interface from guest

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#1024]
When I tried to remove a net interface from a guest, the UI shows an generic error related to not be able to fulfill the request and in the logs there is:

```
Device net3 added successfuly
[14/Sep/2016:11:49:34] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 204, in index
    'PUT': self.update}[method](*args, **kargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 180, in delete
    fn(*self.model_args)
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/model/vmifaces.py", line 228, in delete
    dom.detachDeviceFlags(etree.tostring(iface), flags)
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/model/libvirtconnection.py", line 68, in wrapper
    ret = f(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 1193, in detachDeviceFlags
    if ret == -1: raise libvirtError ('virDomainDetachDeviceFlags() failed', dom=self)
libvirtError: operation failed: no device matching mac address 52:54:00:50:a1:83 found on 0000:00:0c.0
```

**Comment by lcorreia** [comment]
On Ubuntu 16.10 that happens on second try to remove the same interface. The first try successfully removed the interface from the list. When I opened edit window again, the removed interface was back in the list. So the issue may be when listing interfaces.
