### ISSUE TITLE
Unable to add storage volume to NFS pool on RHEL 7.2

### ISSUE THREAD

**Issue by lcorreia** [kimchi-project/kimchi#1035]
KCHVOL0007E: Unable to create storage volume kimchi-makecheck.log in storage pool test-nfs. Details: Failed to create file '/var/lib/kimchi/nfs_mount/test-nfs/kimchi-makecheck.log': Permission denied
Error in async_task 7e6aa3f0-7abb-11e6-92c5-52540036ebff 
Traceback (most recent call last):
  File "/home/dev/wok/src/wok/asynctask.py", line 107, in _run_helper
    self.fn(cb, opaque)
  File "/home/dev/wok/src/wok/plugins/kimchi/model/storagevolumes.py", line 160, in _create_volume_with_capacity
    'err': e.get_error_message()})
OperationFailed: KCHVOL0007E: Unable to create storage volume kimchi-makecheck.log in storage pool test-nfs. Details: Failed to create file '/var/lib/kimchi/nfs_mount/test-nfs/kimchi-makecheck.log': Permission denied

**Comment by alinefm** [comment]
Hi @lcorreia 

Have you followed the instructions at https://github.com/kimchi-project/kimchi/blob/master/docs/README.md#nfs-storage-pool on how to configure the NFS server ?

Seems a permission error as libvirt does not have read-write permission in the NFS dir.
