### ISSUE TITLE
No Administration tab

### ISSUE THREAD

**Issue by GerhardK90** [kimchi-project/kimchi#1056]
I noticed that there are screenshots with the Administration tab, which I do not have (Debian 8) :

![capture](https://cloud.githubusercontent.com/assets/3868214/19542058/a0f03810-966b-11e6-890b-bb2be24fd832.PNG)

Here is my wok-error.log
WOKAUTH0002E: You are not authorized to access Kimchi
[20/Oct/2016:00:52:57] ENGINE Caught signal SIGTERM.
[20/Oct/2016:00:52:57] ENGINE Bus STOPPING
[20/Oct/2016:00:52:58] ENGINE Caught signal SIGTERM.
[20/Oct/2016:00:52:58] ENGINE Bus STOPPING
[20/Oct/2016:00:52:58] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8010)) already shut down
[20/Oct/2016:00:52:58] ENGINE Stopped thread 'Session cleanup'.
[20/Oct/2016:00:52:58] ENGINE Bus STOPPED
[19/Oct/2016:00:52:58] ENGINE Bus EXITING
[20/Oct/2016:00:52:59] ENGINE Bus EXITED
[20/Oct/2016:00:52:59] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8010)) shut down
[20/Oct/2016:00:52:59] ENGINE No thread running for Session cleanup.
[20/Oct/2016:00:52:59] ENGINE Bus STOPPED
[20/Oct/2016:00:52:59] ENGINE Bus EXITING
[20/Oct/2016:00:52:59] ENGINE Bus EXITED
[20/Oct/2016:00:52:59] ENGINE Waiting for child threads to terminate...
Failed to import plugin plugins.ginger.Ginger, error: Class plugins.ginger.Ginger can not be imported, error: cannot import name get_all_model_instances

*** Kimchi: Running feature tests ***
Service Libvirtd running ...: True
Cannot find '' in path: No such file or directory
NFS Target Probe support ...: False
Fibre Channel Host support .: True
Kernel VFIO support ........: True
Network Manager running ....: False
Memory Hotplug support .....: False
*** Kimchi: Feature tests completed ***

*** Ginger Base: Running capabilities tests ***
System Report Tool ...: True
Loading AptUpdate features.
System Update Tool ...: True
Repo Management Tool .: deb
*** Ginger Base: Capabilities tests completed ***
[20/Oct/2016:00:53:14] ENGINE Listening for SIGHUP.
[20/Oct/2016:00:53:14] ENGINE Listening for SIGTERM.
[20/Oct/2016:00:53:14] ENGINE Listening for SIGUSR1.
[20/Oct/2016:00:53:14] ENGINE Bus STARTING
[20/Oct/2016:00:53:15] ENGINE Serving on http://127.0.0.1:8010

*** Kimchi: Running dependable feature tests ***
[20/Oct/2016:00:53:15] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cptools.py", line 175, in handle_func
    handled = self.callable(*args, **self._merged_args(kwargs))
TypeError: staticfile() got multiple values for keyword argument 'filename'

QEMU stream support .......: True
Libvirt Stream Protocols ..: ['http', 'https', 'ftp', 'ftps', 'tftp']
*** Kimchi: Dependable feature tests completed ***

[20/Oct/2016:00:53:16] ENGINE Bus STARTED
[20/Oct/2016:00:53:18] ENGINE Started monitor thread 'Session cleanup'.
WOKAUTH0002E: You are not authorized to access Kimchi
WOKAUTH0002E: You are not authorized to access Kimchi
WOKAUTH0002E: You are not authorized to access Kimchi

Thank you for your help!!

**Comment by alinefm** [comment]
The Administration tab is provided by Ginger. Which is a separated plugin.
Please, check http://kimchi-project.github.io/ginger/ or https://github.com/kimchi-project/ginger/ for more details on how install it.

**Comment by GerhardK90** [comment]
Well I have not mentioned that I have also installed ginger - but there is no Administration tab. I also cannot see related errors in the logs.  Any ideas?
Thank you!
