### ISSUE TITLE
sudo make check failing in Opensuse 42.2

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/kimchi#1116]
```
======================================================================
FAIL: test_vlan_tag_bridge (test_mock_network.MockNetworkTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_mock_network.py", line 67, in test_vlan_tag_bridge
    'interface': iface, 'vlan_id': 987})
  File "test_model_network.py", line 66, in _do_network_test
    self.assertEquals(201, resp.status)
AssertionError: 201 != 400

----------------------------------------------------------------------
Ran 1 test in 3.532s

FAILED (failures=1)
======================================================================
FAIL: test_network_lifecycle (test_model_network.NetworkTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_model_network.py", line 166, in test_network_lifecycle
    _do_network_test(self, model, net)
  File "test_model_network.py", line 66, in _do_network_test
    self.assertEquals(201, resp.status)
AssertionError: 201 != 500

----------------------------------------------------------------------
Ran 4 tests in 9.930s

FAILED (failures=1)
***** Running unit test: test_rest... 	 FAILED
======================================================================
FAIL: test_edit_vm (test_rest.HttpsRestTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_rest.py", line 265, in test_edit_vm
    self.assertEquals(303, resp.status)
AssertionError: 303 != 400

======================================================================
FAIL: test_edit_vm (test_rest.RestTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_rest.py", line 265, in test_edit_vm
    self.assertEquals(303, resp.status)
AssertionError: 303 != 400

----------------------------------------------------------------------
Ran 48 tests in 177.309s

FAILED (failures=2)
[16/Mar/2017:13:27:58] ENGINE Waiting for child threads to terminate...
***** Running unit test: test_storagepoolxml... 	 PASSED - Ran 1 test in 0.001s
***** Running unit test: test_template... 	 FAILED
======================================================================
FAIL: test_customized_network (test_template.TemplateTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_template.py", line 403, in test_customized_network
    self.assertEquals(200, resp.status)
AssertionError: 200 != 400

======================================================================
FAIL: test_customized_tmpl (test_template.TemplateTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_template.py", line 275, in test_customized_tmpl
    self.assertEquals(200, resp.status)
AssertionError: 200 != 400

----------------------------------------------------------------------
Ran 5 tests in 13.178s

FAILED (failures=2)

```

**Comment by biancafc** [comment]
Also failing in CentOS from tarball:

```
$ sudo make check
[sudo] password for bianca:
make  check-recursive
make[1]: Entering directory `/home/bianca/kimchi-2.4.0'
Making check in contrib
make[2]: Entering directory `/home/bianca/kimchi-2.4.0/contrib'
make  check-recursive
make[3]: Entering directory `/home/bianca/kimchi-2.4.0/contrib'
Making check in DEBIAN
make[4]: Entering directory `/home/bianca/kimchi-2.4.0/contrib/DEBIAN'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/home/bianca/kimchi-2.4.0/contrib/DEBIAN'
make[4]: Entering directory `/home/bianca/kimchi-2.4.0/contrib'
make[4]: Nothing to be done for `check-am'.
make[4]: Leaving directory `/home/bianca/kimchi-2.4.0/contrib'
make[3]: Leaving directory `/home/bianca/kimchi-2.4.0/contrib'
make[2]: Leaving directory `/home/bianca/kimchi-2.4.0/contrib'
Making check in control
make[2]: Entering directory `/home/bianca/kimchi-2.4.0/control'
Making check in vm
make[3]: Entering directory `/home/bianca/kimchi-2.4.0/control/vm'
make[3]: Nothing to be done for `check'.
make[3]: Leaving directory `/home/bianca/kimchi-2.4.0/control/vm'
make[3]: Entering directory `/home/bianca/kimchi-2.4.0/control'
make[3]: Nothing to be done for `check-am'.
make[3]: Leaving directory `/home/bianca/kimchi-2.4.0/control'
make[2]: Leaving directory `/home/bianca/kimchi-2.4.0/control'
Making check in distros.d
make[2]: Entering directory `/home/bianca/kimchi-2.4.0/distros.d'
make[2]: Nothing to be done for `check'.
make[2]: Leaving directory `/home/bianca/kimchi-2.4.0/distros.d'
Making check in docs
make[2]: Entering directory `/home/bianca/kimchi-2.4.0/docs'
make[2]: Nothing to be done for `check'.
make[2]: Leaving directory `/home/bianca/kimchi-2.4.0/docs'
Making check in model
make[2]: Entering directory `/home/bianca/kimchi-2.4.0/model'
make[2]: Nothing to be done for `check'.
make[2]: Leaving directory `/home/bianca/kimchi-2.4.0/model'
Making check in po
make[2]: Entering directory `/home/bianca/kimchi-2.4.0/po'
make[2]: Leaving directory `/home/bianca/kimchi-2.4.0/po'
Making check in tests
make[2]: Entering directory `/home/bianca/kimchi-2.4.0/tests'
make  check-am
make[3]: Entering directory `/home/bianca/kimchi-2.4.0/tests'
make  check-local
make[4]: Entering directory `/home/bianca/kimchi-2.4.0/tests'
/usr/bin/mkdir -p ../data/screenshots
./run_tests.sh
***** Running unit test: test_mock_storagevolume... 	 FAILED
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "test_mock_storagevolume.py", line 26, in <module>
    from tests.utils import patch_auth, request, run_server
ImportError: No module named tests.utils
(standard_in) 2: syntax error
./run_tests.sh: line 77: -1: substring expression < 0
***** Running unit test: test_model_storagepool... 	 FAILED
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "test_model_storagepool.py", line 32, in <module>
    from tests.utils import patch_auth, request
ImportError: No module named tests.utils
(standard_in) 1: syntax error
./run_tests.sh: line 77: -1: substring expression < 0
***** Running unit test: test_model_storagevolume... 	 FAILED
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "test_model_storagevolume.py", line 31, in <module>
    from tests.utils import fake_auth_header, HOST
ImportError: No module named tests.utils
(standard_in) 1: syntax error
./run_tests.sh: line 77: -1: substring expression < 0
***** Running unit test: test_model... 	 FAILED
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "test_model.py", line 39, in <module>
    import tests.utils as utils
ImportError: No module named tests.utils
(standard_in) 1: syntax error
./run_tests.sh: line 77: -1: substring expression < 0
***** Running unit test: test_authorization... 	 FAILED
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "test_authorization.py", line 27, in <module>
    from tests.utils import patch_auth
ImportError: No module named tests.utils
(standard_in) 1: syntax error
./run_tests.sh: line 77: -1: substring expression < 0
***** Running unit test: test_mockmodel... 	 FAILED
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "test_mockmodel.py", line 26, in <module>
    from tests.utils import patch_auth, request, run_server
ImportError: No module named tests.utils
(standard_in) 1: syntax error
./run_tests.sh: line 77: -1: substring expression < 0
***** Running unit test: test_vmtemplate... 	 PASSED - Ran 7 tests in 0.015s
(standard_in) 1: syntax error
(standard_in) 1: syntax error
***** Running unit test: test_model_libvirtevents... 	 FAILED
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "test_model_libvirtevents.py", line 30, in <module>
    import tests.utils as utils
ImportError: No module named tests.utils
(standard_in) 1: syntax error
./run_tests.sh: line 77: -1: substring expression < 0
***** Running unit test: test_networkxml... 	 PASSED - Ran 10 tests in 0.003s
(standard_in) 1: syntax error
(standard_in) 1: syntax error
***** Running unit test: test_template... 	 FAILED
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "test_template.py", line 29, in <module>
    from tests.utils import patch_auth, request, run_server
ImportError: No module named tests.utils
(standard_in) 1: syntax error
./run_tests.sh: line 77: -1: substring expression < 0
***** Running unit test: test_mock_network... 	 FAILED
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "test_mock_network.py", line 26, in <module>
    from tests.utils import patch_auth, request, run_server
ImportError: No module named tests.utils
(standard_in) 1: syntax error
./run_tests.sh: line 77: -1: substring expression < 0
***** Running unit test: test_model_network... 	 FAILED
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "test_model_network.py", line 29, in <module>
    from tests.utils import patch_auth, request, rollback_wrapper
ImportError: No module named tests.utils
(standard_in) 1: syntax error
./run_tests.sh: line 77: -1: substring expression < 0
***** Running unit test: test_osinfo... 	 PASSED - Ran 5 tests in 0.055s
(standard_in) 1: syntax error
(standard_in) 1: syntax error
***** Running unit test: test_host... 	 FAILED
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "test_host.py", line 25, in <module>
    from tests.utils import patch_auth, request, run_server
ImportError: No module named tests.utils
(standard_in) 1: syntax error
./run_tests.sh: line 77: -1: substring expression < 0
***** Running unit test: test_rest... 	 FAILED
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "test_rest.py", line 31, in <module>
    from tests.utils import patch_auth, request, run_server, wait_task
ImportError: No module named tests.utils
(standard_in) 1: syntax error
./run_tests.sh: line 77: -1: substring expression < 0
***** Running unit test: test_livemigration... 	 FAILED
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "test_livemigration.py", line 28, in <module>
    from tests.utils import patch_auth, request, rollback_wrapper
ImportError: No module named tests.utils
(standard_in) 1: syntax error
./run_tests.sh: line 77: -1: substring expression < 0
***** Running unit test: test_storagepoolxml... 	 PASSED - Ran 1 test in 0.001s
(standard_in) 1: syntax error
(standard_in) 1: syntax error
***** Running unit test: test_mock_storagepool... 	 FAILED
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "test_mock_storagepool.py", line 26, in <module>
    from tests.utils import patch_auth, request, run_server
ImportError: No module named tests.utils
(standard_in) 1: syntax error
./run_tests.sh: line 77: -1: substring expression < 0
***** Running unit test: test_config... 	 FAILED
======================================================================
FAIL: test_uninstalled_plugin_paths (test_config.ConfigTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_config.py", line 65, in test_uninstalled_plugin_paths
    self.assertEquals(paths.conf_dir, '%s/src/wok/plugins/kimchi' % prefix)
AssertionError: '/etc/wok/plugins.d' != '/usr/share/wok/src/wok/plugins/kimchi'

----------------------------------------------------------------------
Ran 3 tests in 0.002s

FAILED (failures=1)
WARNING: no 'numpy' module, HyBi protocol will be slower
(standard_in) 1: syntax error
(standard_in) 1: syntax error
======================================================================
===================== Kimchi Unit Tests Summary ======================
Ran  tests in  seconds.
test_model_libvirtevents FAILED:  - full log available at /tmp/tmp.b0vNhuQh88
test_model_network FAILED:  - full log available at /tmp/tmp.b0vNhuQh88
test_model_storagepool FAILED:  - full log available at /tmp/tmp.b0vNhuQh88
test_mockmodel FAILED:  - full log available at /tmp/tmp.b0vNhuQh88
test_config FAILED: (failures=1) - full log available at /tmp/tmp.b0vNhuQh88
test_livemigration FAILED:  - full log available at /tmp/tmp.b0vNhuQh88
test_mock_network FAILED:  - full log available at /tmp/tmp.b0vNhuQh88
test_template FAILED:  - full log available at /tmp/tmp.b0vNhuQh88
test_rest FAILED:  - full log available at /tmp/tmp.b0vNhuQh88
test_mock_storagepool FAILED:  - full log available at /tmp/tmp.b0vNhuQh88
test_authorization FAILED:  - full log available at /tmp/tmp.b0vNhuQh88
test_mock_storagevolume FAILED:  - full log available at /tmp/tmp.b0vNhuQh88
test_model FAILED:  - full log available at /tmp/tmp.b0vNhuQh88
test_host FAILED:  - full log available at /tmp/tmp.b0vNhuQh88
test_model_storagevolume FAILED:  - full log available at /tmp/tmp.b0vNhuQh88
make[4]: Leaving directory `/home/bianca/kimchi-2.4.0/tests'
make[3]: Leaving directory `/home/bianca/kimchi-2.4.0/tests'
make[2]: Leaving directory `/home/bianca/kimchi-2.4.0/tests'
Making check in ui
make[2]: Entering directory `/home/bianca/kimchi-2.4.0/ui'
Making check in config
make[3]: Entering directory `/home/bianca/kimchi-2.4.0/ui/config'
make[3]: Nothing to be done for `check'.
make[3]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/config'
Making check in css
make[3]: Entering directory `/home/bianca/kimchi-2.4.0/ui/css'
make[3]: Nothing to be done for `check'.
make[3]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/css'
Making check in images
make[3]: Entering directory `/home/bianca/kimchi-2.4.0/ui/images'
make[3]: Nothing to be done for `check'.
make[3]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/images'
Making check in js
make[3]: Entering directory `/home/bianca/kimchi-2.4.0/ui/js'
make[3]: Nothing to be done for `check'.
make[3]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/js'
Making check in pages
make[3]: Entering directory `/home/bianca/kimchi-2.4.0/ui/pages'
Making check in help
make[4]: Entering directory `/home/bianca/kimchi-2.4.0/ui/pages/help'
Making check in zh_CN
make[5]: Entering directory `/home/bianca/kimchi-2.4.0/ui/pages/help/zh_CN'
make[5]: Nothing to be done for `check'.
make[5]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/pages/help/zh_CN'
Making check in it_IT
make[5]: Entering directory `/home/bianca/kimchi-2.4.0/ui/pages/help/it_IT'
make[5]: Nothing to be done for `check'.
make[5]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/pages/help/it_IT'
Making check in en_US
make[5]: Entering directory `/home/bianca/kimchi-2.4.0/ui/pages/help/en_US'
make[5]: Nothing to be done for `check'.
make[5]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/pages/help/en_US'
Making check in zh_TW
make[5]: Entering directory `/home/bianca/kimchi-2.4.0/ui/pages/help/zh_TW'
make[5]: Nothing to be done for `check'.
make[5]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/pages/help/zh_TW'
Making check in pt_BR
make[5]: Entering directory `/home/bianca/kimchi-2.4.0/ui/pages/help/pt_BR'
make[5]: Nothing to be done for `check'.
make[5]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/pages/help/pt_BR'
Making check in ja_JP
make[5]: Entering directory `/home/bianca/kimchi-2.4.0/ui/pages/help/ja_JP'
make[5]: Nothing to be done for `check'.
make[5]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/pages/help/ja_JP'
Making check in ru_RU
make[5]: Entering directory `/home/bianca/kimchi-2.4.0/ui/pages/help/ru_RU'
make[5]: Nothing to be done for `check'.
make[5]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/pages/help/ru_RU'
Making check in ko_KR
make[5]: Entering directory `/home/bianca/kimchi-2.4.0/ui/pages/help/ko_KR'
make[5]: Nothing to be done for `check'.
make[5]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/pages/help/ko_KR'
Making check in fr_FR
make[5]: Entering directory `/home/bianca/kimchi-2.4.0/ui/pages/help/fr_FR'
make[5]: Nothing to be done for `check'.
make[5]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/pages/help/fr_FR'
Making check in de_DE
make[5]: Entering directory `/home/bianca/kimchi-2.4.0/ui/pages/help/de_DE'
make[5]: Nothing to be done for `check'.
make[5]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/pages/help/de_DE'
Making check in es_ES
make[5]: Entering directory `/home/bianca/kimchi-2.4.0/ui/pages/help/es_ES'
make[5]: Nothing to be done for `check'.
make[5]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/pages/help/es_ES'
make[5]: Entering directory `/home/bianca/kimchi-2.4.0/ui/pages/help'
make[5]: Nothing to be done for `check-am'.
make[5]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/pages/help'
make[4]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/pages/help'
Making check in tabs
make[4]: Entering directory `/home/bianca/kimchi-2.4.0/ui/pages/tabs'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/pages/tabs'
make[4]: Entering directory `/home/bianca/kimchi-2.4.0/ui/pages'
make[4]: Nothing to be done for `check-am'.
make[4]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/pages'
make[3]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/pages'
Making check in spice-html5
make[3]: Entering directory `/home/bianca/kimchi-2.4.0/ui/spice-html5'
Making check in pages
make[4]: Entering directory `/home/bianca/kimchi-2.4.0/ui/spice-html5/pages'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/spice-html5/pages'
make[4]: Entering directory `/home/bianca/kimchi-2.4.0/ui/spice-html5'
make[4]: Nothing to be done for `check-am'.
make[4]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/spice-html5'
make[3]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/spice-html5'
Making check in serial
make[3]: Entering directory `/home/bianca/kimchi-2.4.0/ui/serial'
Making check in html
make[4]: Entering directory `/home/bianca/kimchi-2.4.0/ui/serial/html'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/serial/html'
Making check in libs
make[4]: Entering directory `/home/bianca/kimchi-2.4.0/ui/serial/libs'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/serial/libs'
make[4]: Entering directory `/home/bianca/kimchi-2.4.0/ui/serial'
make[4]: Nothing to be done for `check-am'.
make[4]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/serial'
make[3]: Leaving directory `/home/bianca/kimchi-2.4.0/ui/serial'
make[3]: Entering directory `/home/bianca/kimchi-2.4.0/ui'
make[3]: Nothing to be done for `check-am'.
make[3]: Leaving directory `/home/bianca/kimchi-2.4.0/ui'
make[2]: Leaving directory `/home/bianca/kimchi-2.4.0/ui'
Making check in xmlutils
make[2]: Entering directory `/home/bianca/kimchi-2.4.0/xmlutils'
make[2]: Nothing to be done for `check'.
make[2]: Leaving directory `/home/bianca/kimchi-2.4.0/xmlutils'
make[2]: Entering directory `/home/bianca/kimchi-2.4.0'
while read L && test -n "$L"; do                  \
	dir=mo/$L/LC_MESSAGES ;                       \
	/usr/bin/mkdir -p $dir ;                             \
	ln -sf ../../../po/$L.gmo $dir/kimchi.mo ;   \
done < po/LINGUAS
make  check-local
make[3]: Entering directory `/home/bianca/kimchi-2.4.0'
contrib/check_i18n.py ./i18n.py
Checking for invalid i18n string...
Checking for invalid i18n string successfully
/usr/bin/pep8 --version
1.4.6
/usr/bin/pep8 --filename '*.py,*.py.in' --exclude="*config.py,*i18n.py,*tests/test_config.py" .
./model/vms.py:1376:24: E127 continuation line over-indented for visual indent
./tests/test_rest.py:1284:14: E121 continuation line indentation is not a multiple of four
make[3]: *** [check-local] Error 1
make[3]: Leaving directory `/home/bianca/kimchi-2.4.0'
make[2]: *** [check-am] Error 2
make[2]: Leaving directory `/home/bianca/kimchi-2.4.0'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/home/bianca/kimchi-2.4.0'
make: *** [check] Error 2
```
