### ISSUE TITLE
network_io_counters

### ISSUE THREAD

**Issue by pchard** [kimchi-project/kimchi#1143]
Having some issues.
Installed everything, and it's not working.

Please assist.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/cherrypy/process/plugins.py", line 500, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/kimchi/model/host.py", line 193, in _update_host_stats
    self._get_host_network_io_rate(seconds)
  File "/usr/lib/python2.7/dist-packages/kimchi/model/host.py", line 251, in _get_host_network_io_rate
    net_ios = psutil.network_io_counters(True)
AttributeError: 'module' object has no attribute 'network_io_counters'
```

**Comment by danielhb** [comment]
How did you get this error? Was it when booting a VM, booting Kimchi .... ?

**Comment by nexusdk** [comment]
I just got this on Ubuntu 16.04 after installing Kimchi via apt.
service kimchi status gives the error as described by @pchard

**Comment by alinefm** [comment]
Hi @nexusdk 

Unfortunately, the Kimchi package available via apt is too old and it is not working properly.
We suggest to use the packages available at http://kimchi-project.github.io/kimchi/downloads/ instead to get the newer and stable released version.
