### ISSUE TITLE
libvirtError: Frequent error messages in frontend

### ISSUE THREAD

**Issue by Neuroquila-n8fall** [kimchi-project/kimchi#1149]
I'm trying to figure out why this error is showing up:

`Connection to libvirt broken. Recycling. ecode: 1 edom: 7
[02/Jun/2017:15:42:13] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/wok/control/base.py", line 447, in index
    return self.get(params)
  File "/usr/lib/python2.7/dist-packages/wok/control/base.py", line 421, in get
    resources = self._get_resources(flag_filter)
  File "/usr/lib/python2.7/dist-packages/wok/control/base.py", line 365, in _get_resources
    idents = get_list(*self.model_args, **flag_filter)
  File "/usr/lib/python2.7/dist-packages/wok/plugins/kimchi/model/vms.py", line 223, in get_list
    return VMsModel.get_vms(self.conn)
  File "/usr/lib/python2.7/dist-packages/wok/plugins/kimchi/model/vms.py", line 229, in get_vms
    for dom in conn_.listAllDomains(0):
  File "/usr/lib/python2.7/dist-packages/wok/plugins/kimchi/model/libvirtconnection.py", line 68, in wrapper
    ret = f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/libvirt.py", line 4948, in listAllDomains
    raise libvirtError("virConnectListAllDomains() failed", conn=self)
libvirtError: internal error: client socket is closed
`

The frontend works but shows up the following error message when visiting the Virtualization, Storage or Network tab:

> The server encountered an unexpected condition which prevented it from fulfilling the request.

Sometimes it is necessary to reload the window in order to be able to do anything.
I already cleaned all of the packages.

Any hints?

System is: Ubuntu x64 16.04 [all patched up.]

**Comment by alinefm** [comment]
@Neuroquila-n8fall 

It seems a problem on libvirt connection. I'd suggest to restart the libvirtd service as long as wokd.
Let me know if that helps to solve that.

**Comment by Neuroquila-n8fall** [comment]
Thanks for your help but unfortunately this didn't solve the problem.
