### ISSUE TITLE
Virtualization doesn't work after tweaking the templates.py file

### ISSUE THREAD

**Issue by mattraio** [kimchi-project/kimchi#1217]
Hey,

I've looked over all the fixes by manually changing the templates.py file. When I enter the statements and reload wok, the virtualization tab disappears. When I reset it back, virtualization tab works, but I get the error messages when I try to add an ISO from the var/lib/kimchi/isos. 

It will not change. Is there another way to avoid this check? 
KCHTMPL0020E: Unable to create template due error: KCHIMG0001E: Error probing image OS information: part_list: parted print: /dev/sda: Warning: The driver descriptor says the physical block size is 2048 bytes, but Linux says it is 512 bytes.

**Comment by alinefm** [comment]
Hi @mattraio !

What changes did you do in templates.py?

Usually, when you can not see the virtualization tab it is because Kimchi failed to be loaded.
In that case, it might have a message (on logs) similar to "Unable to load Kimchi plugin due..."

**Comment by mattraio** [comment]
Hello!
I was noticing after I tried a few machines, the Kimchi/Wok provisions a few images (like Windows 7, 8.1) beautifully. However, I wanted a specific ubuntu distro (gnome). After trying over and over again within WOK to create the image, I got an error stating the memory was different.
I searched the github pages and made exact changes to add the ISO entries.
Once that change happens I restarted WOK and I lost the Virtualization tab.
when I reinstall Wok and Kimchi with the default config files, everything is fine.
It seems I can't get the setup to accept other images than the few that are available in a repository somewhere.
Perhaps I'm going about it all wrong and I should just ask for help with accepting custom images.

Oh and when I open virt-manager, the image comes up fine. Just when I try to open it after the config file changes, I loose the virtualization tab.
Please advise.

Get organized with Yahoo Mail 
 
  On Tue, Mar 27, 2018 at 7:42 AM, Aline Manera<notifications@github.com> wrote:   
Hi @mattraio !

What changes did you do in templates.py?

Usually, when you can not see the virtualization tab it is because Kimchi failed to be loaded.
In that case, it might have a message (on logs) similar to "Unable to load Kimchi plugin due..."

**Comment by alinefm** [comment]
Please, check the logs for some message like "Unable to load Kimchi plugin...". There might be on there with more details on what is going on.

**Comment by mattraio** [comment]
Just for clarification...what is the default path to find those logs?

Get organized with Yahoo Mail 
 
  On Tue, Mar 27, 2018 at 1:31 PM, Aline Manera<notifications@github.com> wrote:   
Please, check the logs for some message like "Unable to load Kimchi plugin...". There might be on there with more details on what is going on.

**Comment by alinefm** [comment]
The logs are under /var/log/wok

**Comment by mattraio** [comment]
Sounds good. I'll fire up my server again this weekend and post.

Get organized with Yahoo Mail 
 
  On Wed, Mar 28, 2018 at 8:28 AM, Aline Manera<notifications@github.com> wrote:   
The logs are under /var/log/wok

**Comment by mattraio** [comment]
Okay...now that I've fired up Kimchi and Wok...here is the screenshot attached.
 
I reviewed the logs and this is what I see over and over...

[31/Mar/2018:15:47:25] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/wok/control/base.py", line 447, in index
    return self.get(params)
  File "/usr/lib/python2.7/dist-packages/wok/control/base.py", line 422, in get
    data = self.filter_data(resources, fields_filter)
  File "/usr/lib/python2.7/dist-packages/wok/plugins/kimchi/control/storagevolumes.py", line 57, in filter_data
    fields_filter)
  File "/usr/lib/python2.7/dist-packages/wok/control/base.py", line 400, in filter_data
    if not res.is_authorized():
  File "/usr/lib/python2.7/dist-packages/wok/control/base.py", line 233, in is_authorized
    users = self.data.get("users", None)
  File "/usr/lib/python2.7/dist-packages/wok/plugins/kimchi/control/storagevolumes.py", line 82, in data
    'type': self.info['type'],
KeyError: 'type'
    On Wednesday, March 28, 2018, 9:50:37 AM MDT, Matt Raio <matt.raio@yahoo.com> wrote:  
 
 Sounds good. I'll fire up my server again this weekend and post.

Get organized with Yahoo Mail 
 
  On Wed, Mar 28, 2018 at 8:28 AM, Aline Manera<notifications@github.com> wrote:   
The logs are under /var/log/wok
