### ISSUE TITLE
Kimchi not working - error: No module named 'libvirt'

### ISSUE THREAD

**Issue by Gardinero** [kimchi-project/kimchi#1275]
After installing wok and kimchi from source, I get the following message in my wok-error.log:

`Failed to import plugin wok.plugins.kimchi.Kimchi, error: Class wok.plugins.kimchi.Kimchi can not be imported, error: No module named 'libvirt'`

I do see the plugin under the settings tab as activated. 

Anybody an idea?

In systemd I have have libvirt-bin, libvirtd and libvirt-guests, which all are active.

**Comment by maikgreubel** [comment]
You need to install the libvirt python module. You can do this with

```
pip install libvirt-python
```

**Comment by gianks** [comment]
Hi, i'm stuck this one here (after having passed through the missing libvirt):

```

Running unit test: test_template... FAILED
ERROR: test_template (unittest.loader._FailedTest)
ImportError: Failed to import test module: test_template
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/gianks/kimchi-master/tests/test_template.py", line 27, in <module>
    import iso_gen
  File "/home/gianks/kimchi-master/tests/iso_gen.py", line 22, in <module>
    from wok.plugins.kimchi.isoinfo import IsoImage
  File "/usr/lib/python3/dist-packages/wok/plugins/kimchi/__init__.py", line 19, in <module>
    from wok.plugins.kimchi.root import Kimchi
  File "/usr/lib/python3/dist-packages/wok/plugins/kimchi/root.py", line 24, in <module>
    from wok.plugins.kimchi import config
  File "/usr/lib/python3/dist-packages/wok/plugins/kimchi/config.py", line 27, in <module>
    from wok.config import PluginConfig, PluginPaths
ModuleNotFoundError: No module named 'wok.config'
```

I tried to install wok with:
`pip3 install wok`

but i got:
```
Collecting wok
  Using cached https://files.pythonhosted.org/packages/c5/65/d2768fca3990cd37c8899af8da4507034e5b3c1f038d34b6744e5a840268/wok-1.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    /usr/lib/python3/dist-packages/setuptools/dist.py:484: UserWarning: The version specified (b'1.1.1') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      "details." % self.metadata.version
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-o__83rl6/wok/setup.py", line 37, in <module>
        scripts=['scripts/wok'],
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 984, in run_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 199, in finalize_options
        self.egg_version = self.tagged_version()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 133, in tagged_version
        return safe_version(version + self.vtags)
    TypeError: can't concat str to bytes

```

You said your package doesn't require wok but here seems the opposite... any ideas?

Thanks a lot!
