### ISSUE TITLE
"No such child: driver" error.

### ISSUE THREAD

**Issue by Quicksy** [kimchi-project/kimchi#1277]
I have Wok and Kimchi installed on Ubuntu 18.04. It used to work fine on last week, but today when I'm trying to clone my VM or even navigate to the "Virtualization -> Guests" tab, I get red message "No such child: driver":
![image](https://user-images.githubusercontent.com/34827700/62864263-46702780-bd1c-11e9-811f-bfd7d838a8f5.png)
I can see the following messages in wok-error.log:
```
Error in async_task b712184a-bcf9-11e9-a989-04d4c4afc3b2 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/wok/asynctask.py", line 107, in _run_helper
    self.fn(cb, opaque)
  File "/usr/lib/python2.7/dist-packages/wok/plugins/kimchi/model/vms.py", line 409, in _clone_task
    xml = self._clone_update_disks(xml, rollback)
  File "/usr/lib/python2.7/dist-packages/wok/plugins/kimchi/model/vms.py", line 499, in _clone_update_disks
    orig_vol = self.storagevolume.lookup(orig_pool_name, orig_vol_name)
  File "/usr/lib/python2.7/dist-packages/wok/plugins/kimchi/model/storagevolumes.py", line 335, in lookup
    used_by = get_disk_used_by(self.conn, path)
  File "/usr/lib/python2.7/dist-packages/wok/plugins/kimchi/model/diskutils.py", line 38, in get_disk_used_by
    d_info = get_vm_disk_info(dom, disk)
  File "/usr/lib/python2.7/dist-packages/wok/plugins/kimchi/xmlutils/disk.py", line 165, in get_vm_disk_info
    'format': disk.driver.attrib['type'],
  File "src/lxml/objectify.pyx", line 230, in lxml.objectify.ObjectifiedElement.__getattr__
  File "src/lxml/objectify.pyx", line 450, in lxml.objectify._lookupChildOrRaise
AttributeError: no such child: driver
```
Could you help me to understand what happened and how can I fix this?

**Comment by Quicksy** [comment]
Yes, 
```# dpkg -l | grep kimchi
ii  kimchi                                2.5.0                                       all          Kimchi web application

# dpkg -l | grep wok
ii  wok                                   2.5.0                                       all          Wok - Webserver Originated from Kimchi```

**Comment by alinefm** [comment]
I've just finished up the tests of the next release on Ubuntu 19.10 and it is working fine. Could you give it a try?
