### ISSUE TITLE
__init__() got an unexpected keyword argument 'target_cfg'

### ISSUE THREAD

**Issue by marmalodak** [kimchi-project/kimchi#1280]
I started kimchi for the first time. My only change to the configuration was to `/etc/kimchi/template.conf` where I added the line

    networks=snapnet,

This is on up-to-date Fedora 30.

    $ journalctl -u kimchid -n 1000
    -- Logs begin at Sun 2018-11-11 08:21:24 PST. --
    Aug 26 14:17:40 mediapc systemd[1]: Started Kimchi server.
    Aug 26 14:17:41 mediapc kimchid[6358]: libvirt: Network Driver error : Network not found: no network with matching name 'default'
    Aug 26 14:17:41 mediapc systemd[1]: kimchid.service: Main process exited, code=exited, status=1/FAILURE
    Aug 26 14:17:41 mediapc systemd[1]: kimchid.service: Failed with result 'exit-code'.
    Aug 26 14:23:34 mediapc systemd[1]: Started Kimchi server.
    Aug 26 14:23:35 mediapc kimchid[9057]: libvirt: Storage Driver error : Storage pool not found: no storage pool with matching name 'ISO'
    Aug 26 14:23:35 mediapc kimchid[9057]: Process Process-1:
    Aug 26 14:23:35 mediapc kimchid[9057]: Traceback (most recent call last):
    Aug 26 14:23:35 mediapc kimchid[9057]:   File "/usr/lib64/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    Aug 26 14:23:35 mediapc kimchid[9057]:     self.run()
    Aug 26 14:23:35 mediapc kimchid[9057]:   File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    Aug 26 14:23:35 mediapc kimchid[9057]:     self._target(*self._args, **self._kwargs)
    Aug 26 14:23:35 mediapc kimchid[9057]:   File "/usr/lib/python2.7/site-packages/kimchi/vnc.py", line 53, in start_proxy
    Aug 26 14:23:35 mediapc kimchid[9057]:     server = WebSocketProxy(**params)
    Aug 26 14:23:35 mediapc kimchid[9057]:   File "/usr/lib/python2.7/site-packages/websockify/websocketproxy.py", line 265, in __init__
    Aug 26 14:23:35 mediapc kimchid[9057]:     websocket.WebSocketServer.__init__(self, RequestHandlerClass, *args, **kwargs)
    Aug 26 14:23:35 mediapc kimchid[9057]: TypeError: __init__() got an unexpected keyword argument 'target_cfg'
    Aug 26 14:23:36 mediapc kimchid[9057]: Exception in thread Thread-1:
    Aug 26 14:23:36 mediapc kimchid[9057]: Traceback (most recent call last):
    Aug 26 14:23:36 mediapc kimchid[9057]:   File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    Aug 26 14:23:36 mediapc kimchid[9057]:     self.run()
    Aug 26 14:23:36 mediapc kimchid[9057]:   File "/usr/lib/python2.7/site-packages/cherrypy/process/plugins.py", line 500, in run
    Aug 26 14:23:36 mediapc kimchid[9057]:     self.function(*self.args, **self.kwargs)
    Aug 26 14:23:36 mediapc kimchid[9057]:   File "/usr/lib/python2.7/site-packages/kimchi/model/host.py", line 193, in _update_host_stats
    Aug 26 14:23:36 mediapc kimchid[9057]:     self._get_host_disk_io_rate(seconds)
    Aug 26 14:23:36 mediapc kimchid[9057]:   File "/usr/lib/python2.7/site-packages/kimchi/model/host.py", line 234, in _get_host_disk_io_rate
    Aug 26 14:23:36 mediapc kimchid[9057]:     disk_io = psutil.disk_io_counters(False)
    Aug 26 14:23:36 mediapc kimchid[9057]:   File "/usr/lib64/python2.7/site-packages/psutil/__init__.py", line 2014, in disk_io_counters
    Aug 26 14:23:36 mediapc kimchid[9057]:     rawdict = _psplatform.disk_io_counters()
    Aug 26 14:23:36 mediapc kimchid[9057]:   File "/usr/lib64/python2.7/site-packages/psutil/_pslinux.py", line 1076, in disk_io_counters
    Aug 26 14:23:36 mediapc kimchid[9057]:     raise ValueError("not sure how to interpret line %r" % line)
    Aug 26 14:23:36 mediapc kimchid[9057]: ValueError: not sure how to interpret line '   8       0 sda 109152 1475 4522860 63406 226188 103339 7368064 13651617 0 156597 13588459 0 0 0 0\n'

**Comment by alinefm** [comment]
Could you, please, try it out: https://github.com/kimchi-project/kimchi/releases/tag/3.0.0 ? It was tested on Fedora 31 and it worked fine.
