### ISSUE TITLE
Kimchi/Wok 3.0 on Ubuntu 18.04 installation error

### ISSUE THREAD

**Issue by MariuCh007** [kimchi-project/kimchi#1297]
An error related to the python3-cheetah package occurs when installing wok 3.0 on Ubuntu 18.04.3 LTS.

1. Installation:
sudo apt install -y ./wok-3.0.0-0.ubuntu.noarch.deb
2. See error:

> "
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'wok' instead of './wok-3.0.0-0.ubuntu.noarch.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 **wok : Depends: python3-cheetah but it is not installable**
E: Unable to correct problems, you have held broken packages.
> "

How to solve this problem?

**Comment by alinefm** [comment]
You will need to install cheetah using pip3 `sudo -H pip3 install cheetah` and you will need to ignore dependencies if you still want to use the deb package available.(`--fix-broken` or `--ignore-missing`)

**Comment by MariuCh007** [comment]
Thank you for your response.
I'm not fluent in Linux, but the command:
> sudo apt install --ignore-missing ./wok-3.0.0-0.ubuntu.noarch.deb 

> 
or

> sudo apt install --fix-broken ./wok-3.0.0-0.ubuntu.noarch.deb

ends with an error as above - error message unchanged.

**Comment by tabnul** [comment]
same issue here. i was unable to install cheetah under 18.0.4. seems to be incompatible.
moved to 19.10 and with some manual actions i got it running eventually. not a smooth experience.

**Comment by alinefm** [comment]
> Thank you for your response.
> I'm not fluent in Linux, but the command:
> 
> > sudo apt install --ignore-missing ./wok-3.0.0-0.ubuntu.noarch.deb
> 
> > 
> 
> or
> 
> > sudo apt install --fix-broken ./wok-3.0.0-0.ubuntu.noarch.deb
> 
> ends with an error as above - error message unchanged.

Have you tried to install cheetah using pip `sudo -H pip3 install cheetah` ?

**Comment by MariuCh007** [comment]
I receive this error:

> Collecting cheetah
  Using cached https://files.pythonhosted.org/packages/cd/b0/c2d700252fc251e91c08639ff41a8a5203b627f4e0a2ae18a6b662ab32ea/Cheetah-2.4.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7tj84es2/cheetah/setup.py", line 10, in <module>
        import SetupTools
      File "/tmp/pip-build-7tj84es2/cheetah/SetupTools.py", line 50
        except DistutilsPlatformError, x:
                                     ^
    SyntaxError: invalid syntax
**Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7tj84es2/cheetah/**
"

**Comment by alinefm** [comment]
Seems like you are trying to install python2 version. Could you check it?

`pip --version`

or make sure to use `pip3`

I think the right package should be https://pypi.org/project/Cheetah3/

**Comment by MariuCh007** [comment]
`> pip --version`
`pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.7)`

`> pip3 search cheetah`
```
Cheetah (2.4.4)                  - Cheetah is a template engine and code generation tool.
cheetah-lint (0.5.0)             - Linting tools for the Cheetah templating language.
yelp_cheetah (0.18.0)            - cheetah, hacked by yelpers
ice.template (0.1.0)             - Persistent Cheetah templates
Cheetah3 (3.2.4)                 - Cheetah is a template engine and code generation tool
  INSTALLED: 3.2.4 (latest)
TurboCheetah (1.0)               - TurboGears plugin to support use of Cheetah templates
isotoma.recipe.template (0.0.5)  - Wrapper around Cheetah + JSON to provide simple buildout templating
pyxl (1.0)                       - Pyxl is an open source package that extends Python to support inline HTML. It
                                   converts         HTML fragments into valid Python expressions, and is meant as a
                                   replacement for traditional         python templating systems like Mako or Cheetah.
                                   It automatically escapes data, enforces         correct markup and makes it easier
                                   to write reusable and well structured UI code.         Pyxl was inspired by the XHP
                                   project at Facebook.
```

**Comment by ttmcmurry** [comment]
Apologies if this is a "Me too" for an open issue.  I'm having the exact same errors, verbatim, as MariuCh007 on Ubuntu 18.04.04 LTS.

**Comment by djegy** [comment]
try sudo -H pip3 install cheetah3 and dpkg --ignore-depends=python3-cheetah -i wok-3.0.0-0.ubuntu.noarch.deb
ButI still have a problem with Kimchi

**Comment by divadsn** [comment]
Isn't Ubuntu 18.04 having overall an unfixed issue with libvirt till 19.10?

**Comment by SmokeyBR** [comment]
Has anyone gotten around this issue ?
