### ISSUE TITLE
NFS storage pool does not function

### ISSUE THREAD

**Issue by tabnul** [kimchi-project/kimchi#1303]
**Describe the bug**
I am unable to mount NFS storage directly. I receive an error. Underlying mount command seems fine.
Ubuntu 19.10 AMD64 fresh install.
wok/kimchi 3.0.0

**To Reproduce**
1. go to storage
2. add storage, give a name, select nfs
3. fill in server: 192.168.254.89 (or something different)
4. fill in relative path: /test
5. click ok. Error Gui: The server encountered an unexpected condition which prevented it from fulfilling the request.

Error wok errorlog:
```
[19/Jan/2020:19:41:49] HTTP
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3/dist-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/wok/control/base.py", line 490, in index
    result = self.create(params, *args)
  File "/usr/lib/python3/dist-packages/wok/plugins/kimchi/control/storagepools.py", line 62, in create
    name = create(*args)
  File "/usr/lib/python3/dist-packages/wok/plugins/kimchi/model/storagepools.py", line 203, in create
    poolDef.prepare(conn)
  File "/usr/lib/python3/dist-packages/wok/plugins/kimchi/model/libvirtstoragepool.py", line 109, in prepare
    mounts = parse_cmd_output(rawMounts, output_items)
  File "/usr/lib/python3/dist-packages/wok/utils.py", line 482, in parse_cmd_output
    for line in output.split('\n'):
TypeError: a bytes-like object is required, not 'str'
```

6. If i add a : to the servername (as a test) i get of course an error in the log as well.  But in that case it prints the exact command, the syntax seems fine because when i manually execute that command (without the ':') it mounts just fine.

**Expected behavior**
Mounting fine

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [latest]

**Additional context**

**Comment by alinefm** [comment]
Thank for reporting, @tabnul 

It is already fixed by https://github.com/kimchi-project/kimchi/commit/0402b421702ed0ecd8c44a98adc1523ac675c425

Once we get more bug fixes ready to go, a new release will be out.
