### ISSUE TITLE
source build with could not connect to spice or vnc

### ISSUE THREAD

**Issue by Hero9909** [kimchi-project/kimchi#1323]
**Describe the bug**
the web vnc or spice connection does not work as intendet, and breaks the connection up after a few frames

**To Reproduce**
1. Go to guests
2. Click on "view console"
3. new tab opens
4. connection chrashes / no vnc connection is initialized
**Expected behavior**
as tested i would like to see a guest desktop / video here

**Desktop (please complete the following information):**
 - OS: 1. Ubuntu 20.04 server from live installaion and 2. ubuntu 20.04 qemu host for 1 
 - Browser 2. chromium Version 81.0.4044.138
 - Version 5e06451 build from source with fix from #1319 

**Additional context**
Log:
```
[13/May/2020:06:53:36] HTTP 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3/dist-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/cherrypy/_cptools.py", line 182, in handle_func
    handled = self.callable(*args, **self._merged_args(kwargs))
TypeError: staticfile() got multiple values for argument 'filename'
[13/May/2020:06:53:36] HTTP 
Request Headers:
  Remote-Addr: 127.0.0.1
  HOST: 192.168.122.48
  X-REAL-IP: 192.168.122.1
  X-FORWARDED-FOR: 192.168.122.1
  CONNECTION: close
  USER-AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/81.0.4044.138 Chrome/81.0.4044.138 Safari/537.36
  ACCEPT: image/webp,image/apng,image/*,*/*;q=0.8
  SEC-FETCH-SITE: same-origin
  SEC-FETCH-MODE: no-cors
  SEC-FETCH-DEST: empty
  REFERER: https://192.168.122.48:8001/plugins/kimchi/spice_auto.html?port=8001&listen=192.168.122.48&token=dWJ1bnR1MTkuMDQuMTU4OTM0OTUxMzQzOS12bS0x&encrypt=1
  ACCEPT-ENCODING: gzip, deflate, br
  ACCEPT-LANGUAGE: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
  COOKIE: username=devadmin; user_role=admin; token=dWJ1bnR1MTkuMDQuMTU4OTM0OTUxMzQzOS12bS0x; wok=4a9b93061e404cba36c4c83b73a7c521a359340c; lastPage="/#plugins/kimchi/tabs/guests"
```

**Comment by NZLostboy** [comment]
Having the same issue, haven't manage to resolve it yet.

**Comment by Criptos** [comment]
x3...  Me tooo  :)

**Comment by nrdmtt** [comment]
x4 same here 

--- EDIT--- 

For those that are stuck with this noVNC problem and are running kimchi on a headless machine, I found a temporary solution to at least complete the first installation.  [Here](https://blog.scottlowe.org/2013/08/21/accessing-vnc-consoles-of-kvm-guests-via-ssh/) you can find the way to create an SSH tunnel that you can later use with your VNC client to connect to the VM. 

One you have connected, you might see some errors. Just hit TAB and then select the boot option. 

Hope it can help.

**Comment by mengxing2017** [comment]
这个问题有可能是websockify版本问题，使用websockify 0.7.0版本就不报这个错误了，解决办法：
```shell
sudo pip3 install websockify==0.7.0
```

**Comment by Nebdir** [comment]
> 这个问题有可能是websockify版本问题，使用websockify 0.7.0版本就不报这个错误了，解决办法：
> 

This problem may be caused by the websockify version. If you use the websockify 0.7.0 version, this error will not be reported. Solution

> ```shell
> sudo pip3 install websockify==0.7.0
> ```

please write in english the next time, thank you.

but anyway ill try that out
