### ISSUE TITLE
Virtualization tab is not available 

### ISSUE THREAD

**Issue by tamhankarni3** [kimchi-project/kimchi#1337]
I have followed the instruction given on link.
I have installed "Ubuntu 18.04.4 LTS" and installed WOK as well as KIMCHI 3.0

Unable to see **Virtualization Tab**

here is the output of **python3 /usr/bin/wokd --environment=dev** command

root@POWER8:~# python3 /usr/bin/wokd --environment=dev
Push server created on address /run/user/0/woknotifications
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/wok/websocket.py", line 96, in start_proxy
    server.start_server()
  File "/usr/lib/python3/dist-packages/websockify/websocket.py", line 976, in start_server
    tcp_keepintvl=self.tcp_keepintvl)
  File "/usr/lib/python3/dist-packages/websockify/websocket.py", line 744, in socket
    sock.bind(addrs[0][4])
OSError: [Errno 98] Address already in use
Failed to import plugin wok.plugins.kimchi.Kimchi, error: Class wok.plugins.kimchi.Kimchi can not be imported, error: No module named 'libvirt'
Plugin configuration file /etc/wok/plugins.d/__pycache__.conf doesn't exist.
[01/Dec/2020:20:31:09] ENGINE Listening for SIGTERM.
[01/Dec/2020:20:31:09] ENGINE Listening for SIGHUP.
[01/Dec/2020:20:31:09] ENGINE Listening for SIGUSR1.
[01/Dec/2020:20:31:09] ENGINE Bus STARTING
[01/Dec/2020:20:31:09] ENGINE Started monitor thread 'Autoreloader'.
[01/Dec/2020:20:31:14] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x78e07d025f98>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/process/wspbus.py", line 216, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python3/dist-packages/cherrypy/_cpserver.py", line 177, in start
    super(Server, self).start()
  File "/usr/lib/python3/dist-packages/cherrypy/process/servers.py", line 169, in start
    wait_for_free_port(*self.bind_addr)
  File "/usr/lib/python3/dist-packages/cherrypy/process/servers.py", line 464, in wait_for_free_port
    raise IOError('Port %r not free on %r' % (port, host))
OSError: Port 8010 not free on '127.0.0.1'

[01/Dec/2020:20:31:14] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/process/wspbus.py", line 254, in start
    self.publish('start')
  File "/usr/lib/python3/dist-packages/cherrypy/process/wspbus.py", line 234, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: OSError("Port 8010 not free on '127.0.0.1'",)

[01/Dec/2020:20:31:14] ENGINE Bus STOPPING
[01/Dec/2020:20:31:14] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8010)) already shut down
[01/Dec/2020:20:31:14] ENGINE Stopped thread 'Autoreloader'.
[01/Dec/2020:20:31:14] ENGINE Bus STOPPED
[01/Dec/2020:20:31:14] ENGINE Bus EXITING
[01/Dec/2020:20:31:14] ENGINE Bus EXITED
root@POWER8:~#

**Comment by Pomdre** [comment]
Port 8010 not free on '127.0.0.1
