### ISSUE TITLE
Creating a guest OS whose name contain spaces causes it to fail

### ISSUE THREAD

**Issue by orpiske** [kimchi-project/kimchi#306]
Creating a guest OS whose name contain spaces causes Kimchi to fail to start the guest OS. The UI displays a message stating that it "Failed to start": 

![kimchi-failed_to_start](https://f.cloud.github.com/assets/1851560/1930229/553b72e2-7ea7-11e3-9726-55ec63aa5401.png)

This is the Kimchid startup log: 

```
[15/Jan/2014:12:29:47] HTTP 
Request Headers:
  COOKIE: kimchi=3a38037087445fd43b186a58eb0bee1953d055d2; userid=orpiske; token=windows7
  Remote-Addr: 127.0.0.1
  Content-Length: 0
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:26.0) Gecko/20100101 Firefox/26.0
  CONNECTION: keep-alive
  REFERER: https://localhost:8001/
  PRAGMA: no-cache
  X-REQUESTED-WITH: XMLHttpRequest
  HOST: localhost:8001
  CACHE-CONTROL: no-cache
  ACCEPT: application/json, text/javascript, */*; q=0.01
  ACCEPT-LANGUAGE: en-us,en;q=0.7,pt-br;q=0.3
  Content-Type: application/json
  ACCEPT-ENCODING: gzip, deflate
[15/Jan/2014:12:29:47] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/orpiske/workspace/code/foss/kimchi/src/kimchi/control/base.py", line 70, in wrapper
    fn(*model_args)
  File "/home/orpiske/workspace/code/foss/kimchi/src/kimchi/model.py", line 579, in vm_start
    dom.create()
  File "/home/orpiske/workspace/code/foss/kimchi/src/kimchi/model.py", line 1771, in wrapper
    ret = f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/libvirt.py", line 620, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirtError: internal error cannot load AppArmor profile 'libvirt-61d77fad-bb1f-49fa-93e1-2b70a5cb8f4c'
```

I believe Kimchi should prevent users from using certain characters in the Guest OS name, just like Virtual Machine Manager does. Here's an attached image for reference: ![vmm-error](https://f.cloud.github.com/assets/1851560/1930257/fd537330-7ea7-11e3-88af-68ab47dd9fe0.png)

**Comment by hlogmans** [comment]
Hmm, ran into this issue (Ubuntu 14.04) after a (=compliment) flawless experience with kimchi. For new users, this can be typed as 'scary error'. Anyone considered to catch this error and amend it with the tip "Not all host OS-es can use spaces in the VM name". Then you don't have to change anything when this problem in Ubuntu is fixed, and don't have to impose restrictions on all users. And the error is much less scary ;-)

**Comment by ss23** [comment]
I am strongly in favor for adding a temporary restriction/notification when running on Ubuntu. The error is exceptionally hard to figure out for someone new to Kimchi.

**Comment by ET-Bent** [comment]
As @ss23 told I ran into it. Without proper knowledge, this is a "never to be figured out" bug. Please add a restriction to the name field to disallow spaces.
