### ISSUE TITLE
"make check" fails on RHEL7

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#493]
# 
## ERROR: test_template_update (test_model.ModelTests)

[01/Dec/2014:11:20:08] ENGINE Waiting for thread MainThread.
Traceback (most recent call last):
  File "test_model.py", line 926, in test_template_update
    inst.template_update('new-test', params)
  File "/root/kimchi/src/kimchi/model/templates.py", line 210, in update
    ident = self.templates.create(new_t)
  File "/root/kimchi/src/kimchi/model/templates.py", line 66, in create
    check_topology(params['cpus'], topology)
  File "/root/kimchi/src/kimchi/model/cpuinfo.py", line 124, in check_topology
    raise InvalidParameter("KCHCPUINF0002E")
InvalidParameter: KCHCPUINF0002E: Invalid vCPU/topology combination.
# 
## ERROR: test_vm_cdrom (test_model.ModelTests)

Traceback (most recent call last):
  File "test_model.py", line 504, in test_vm_cdrom
    cdrom_dev = inst.vmstorages_create(vm_name, cdrom_args)
  File "/root/kimchi/src/kimchi/model/vmstorages.py", line 144, in create
    raise OperationFailed("KCHVMSTOR0008E", {'error': e.message})
OperationFailed: KCHVMSTOR0008E: Error while creating new storage device: XML error: unknown protocol type 'http'
# 
## ERROR: test_vm_disk (test_model.ModelTests)

Traceback (most recent call last):
  File "test_model.py", line 390, in test_vm_disk
    disk = _attach_disk()
  File "test_model.py", line 329, in _attach_disk
    disk = inst.vmstorages_create(vm_name, disk_args)
  File "/root/kimchi/src/kimchi/model/vmstorages.py", line 144, in create
    raise OperationFailed("KCHVMSTOR0008E", {'error': e.message})
OperationFailed: KCHVMSTOR0008E: Error while creating new storage device: internal error: unable to execute QEMU command '__com.redhat_drive_add': could not open disk image /root/kimchi/tests/kimchi-images/test-volume.img: Could not open file: Permission denied

---

**Comment by ramonmedeiros** [comment]
I just run make check on RHEL 7.1 with HEAD: 19ded0b98b5d9a149bb1efdbb62331bad9869843 and did not reproduced it.
