### ISSUE TITLE
Fail to login because of session id lookup failure

### ISSUE THREAD

**Issue by lvroyce** [kimchi-project/kimchi#531]
### Description

When using PAM login, supply admin id and passwd, login fails
### How to reproduce
-  Install kimchi in Ubuntu 14.10
-  start kimchid
-  visit kimchid with firefox
-  try to login with admin user and pwd
### Expected result
-  login successfully
### Actual result

Request cookie:
kimchi: 5b5663b561901ab5470b569f4d379617d8a015a1
username: royce

Response cookie:
kimchi: 517d2700d63f0161cfe6304e1a70ef6525ebfba3
expires: 2014-12-04T06:38:12.000Z
httpOnly: True

Try login, or logout and clear cookies, Server will raise 500 error with backend log:
9.115.122.147 - - [04/Dec/2014:14:25:26] "POST /login HTTP/1.0" 500 1049 "https://9.115.122.184:8001/login.html" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:30.0) Gecko/20100101 Firefox/30.0"
[04/Dec/2014:14:25:26]  Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 104, in run
    hook()
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 63, in __call__
    return self.callback(**self.kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/sessions.py", line 793, in close
    sess.release_lock()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/sessions.py", line 432, in release_lock
    self.locks[self.id].release()
KeyError: u'5b5663b561901ab5470b569f4d379617d8a015a1'

[04/Dec/2014:14:25:26]  Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cptree.py", line 144, in release_serving
    req.close()
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 506, in close
    self.hooks.run('on_end_request')
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 114, in run
    raise exc
KeyError: u'5b5663b561901ab5470b569f4d379617d8a015a1'

**Comment by cd1** [comment]
Can you still reproduce this issue (even if it's 50% of the time)? Make sure you try to reproduce it on the latest version of your distro (e.g. Ubuntu 14.10).
