### ISSUE TITLE
FC20: test case fails for template

### ISSUE THREAD

**Issue by lvroyce** [kimchi-project/kimchi#568]
ERROR: test_template_update (test_model.ModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_model.py", line 946, in test_template_update
    inst.template_update('new-test', params)
  File "/home/royce/kimchi-use-bisect/kimchi/src/kimchi/model/templates.py", line 210, in update
    ident = self.templates.create(new_t)
  File "/home/royce/kimchi-use-bisect/kimchi/src/kimchi/model/templates.py", line 66, in create
    check_topology(params['cpus'], topology)
  File "/home/royce/kimchi-use-bisect/kimchi/src/kimchi/model/cpuinfo.py", line 124, in check_topology
    raise InvalidParameter("KCHCPUINF0002E")
InvalidParameter: KCHCPUINF0002E: Invalid vCPU/topology combination.

**Comment by cd1** [comment]
This issue is also reported by issue #493.

Also, please report issues for Fedora 21, which is the latest version of that distro.

**Comment by alinefm** [comment]
Closing based on last comment.
