### ISSUE TITLE
Kimchi on ppc64el

### ISSUE THREAD

**Issue by frediz** [kimchi-project/kimchi#573]
Hi :)
while working on debian packaging of kimchi, I tested it on ppc64el and the first issue I came up with is the following : 
```
16/Jan/2015:13:11:48] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/kimchi/control/base.py", line 152, in index
    self.lookup()
  File "/usr/lib/python2.7/dist-packages/kimchi/control/base.py", line 128, in lookup
    self.info = lookup(*self.model_args)
  File "/usr/lib/python2.7/dist-packages/kimchi/model/config.py", line 111, in lookup
    'qemu_spice': self._qemu_support_spice(),
  File "/usr/lib/python2.7/dist-packages/kimchi/model/config.py", line 83, in _qemu_support_spice
    qemu_path = find_qemu_binary(find_emulator=True)
  File "/usr/lib/python2.7/dist-packages/kimchi/config.py", line 80, in find_qemu_binary
    raise Exception("Unable to get qemu binary location: %s" % e)
Exception: Unable to get qemu binary location: list index out of range
```
from the short debug I did, it tries to find qemu-system-ppc64el.
On ppc64el though, the binary is qemu-system-ppc64.
ppc64el will be official in debian 8 and if I'm right, PowerKVM 3 will be little endian too, so that'd be nice to have kimchi for them.
I can provide help and access to the host on which I had this. Just let me know.

Fred

**Comment by ramonmedeiros** [comment]
Hi Frediz,

can you give me access on a P8 system to run a test?

**Comment by frediz** [comment]
Sure, let me send you access infos in private.

F.

**Comment by ramonmedeiros** [comment]
Hi Frediz,

just received the infos. Thanks.

After passing the issue you reported, i found others (this one while creating a template with remote fedora 20 ISO) :

[19/Jan/2015:10:16:30] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/kimchi/control/base.py", line 327, in index
    return self.create(parse_request(), *args)
  File "/usr/lib/python2.7/dist-packages/kimchi/control/base.py", line 259, in create
    name = create(*args)
  File "/usr/lib/python2.7/dist-packages/kimchi/model/templates.py", line 93, in create
    t = LibvirtVMTemplate(params, scan=True)
  File "/usr/lib/python2.7/dist-packages/kimchi/model/templates.py", line 230, in __init__
    VMTemplate.__init__(self, args, scan)
  File "/usr/lib/python2.7/dist-packages/kimchi/vmtemplate.py", line 61, in __init__
    entry = osinfo.lookup(os_distro, os_version)
  File "/usr/lib/python2.7/dist-packages/kimchi/osinfo.py", line 97, in lookup
    if distro in modern_version_bases[arch]:
KeyError: None

This will take a little long.

**Comment by ramonmedeiros** [comment]
The patch is already on the mailing list (seems that is able to be applied)

http://lists.ovirt.org/pipermail/kimchi-devel/2015-January/009552.html
