### ISSUE TITLE
Kimchi on ppc64 - test_vm_disk fails

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/kimchi#574]
This is the result of the test running in a ppc64le system:

$ ./run_tests.sh test_model.ModelTests.test_vm_diskLoading YumUpdate features.
E
======================================================================
ERROR: test_vm_disk (test_model.ModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_model.py", line 380, in test_vm_disk
    inst.templates_create(params)
  File "/root/kimchi/src/kimchi/model/templates.py", line 93, in create
    t = LibvirtVMTemplate(params, scan=True)
  File "/root/kimchi/src/kimchi/model/templates.py", line 230, in __init__
    VMTemplate.__init__(self, args, scan)
  File "/root/kimchi/src/kimchi/vmtemplate.py", line 56, in __init__
    distro, version = self._get_os_info(args, scan)
  File "/root/kimchi/src/kimchi/vmtemplate.py", line 87, in _get_os_info
    distro, version = self.get_iso_info(iso)
  File "/root/kimchi/src/kimchi/vmtemplate.py", line 120, in get_iso_info
    iso_img = IsoImage(iso)
  File "/root/kimchi/src/kimchi/isoinfo.py", line 149, in __init__
    self._scan()
  File "/root/kimchi/src/kimchi/isoinfo.py", line 435, in _scan
    self._scan_ppc()
  File "/root/kimchi/src/kimchi/isoinfo.py", line 302, in _scan_ppc
    self._unpack(DIR_NAMELEN_LOCATION_PARENT, dir_data)
  File "/root/kimchi/src/kimchi/isoinfo.py", line 181, in _unpack
    return s.unpack(data[:s.size])
error: unpack requires a string argument of length 8

----------------------------------------------------------------------
Ran 1 test in 1.935s

FAILED (errors=1)

I am investigating the issue to see if it's a machine configuration problem or a issue with Kimchi.

**Comment by danielhb** [comment]
Good news: the error is reproducible in 'regular' ppc64. I'll update the entry accordingly and will investigate it in both archs

**Comment by danielhb** [comment]
Patch sent to Kimchi ML:

tests/iso_gen.py: adding fake bootable PowerPC ISO

**Comment by ramonmedeiros** [comment]
Seems that the issue is related with user, not Selinux. I tested changing /etc/libvirt/qemu.conf default users, from qemu to root. Went ok.

**Comment by danielhb** [comment]
Patch was pushed upstream and now the test is back to failing as described in bug #507 . We can close this bug.
