### ISSUE TITLE
Unable to create bridged VLAN network after creating a bridged network

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#621]
1. Create a bridged network (without VLAN tag).
2. Activate it.
3. Try to create a bridged VLAN network

An error is displayed:
{
  "reason":"The server encountered an unexpected condition which prevented it from fulfilling the request.",
  "code":"500 Internal Server Error"
}    

And on Kimchi logs there is the traceback:

[16/Mar/2015:17:05:32] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/kimchi/control/base.py", line 330, in index
    return self.create(parse_request(), *args)
  File "/usr/lib/python2.7/site-packages/kimchi/control/base.py", line 262, in create
    name = create(*args)
  File "/usr/lib/python2.7/site-packages/kimchi/model/networks.py", line 101, in create
    self._set_network_bridge(params)
  File "/usr/lib/python2.7/site-packages/kimchi/model/networks.py", line 187, in _set_network_bridge
    str(params['vlan_id']))
  File "/usr/lib/python2.7/site-packages/kimchi/model/networks.py", line 213, in _create_vlan_tagged_bridge
    if br_name in [net.bridgeName() for net in conn.listAllNetworks()]:
  File "/usr/lib/python2.7/site-packages/kimchi/model/libvirtconnection.py", line 66, in wrapper
    ret = f(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 2780, in bridgeName
    if ret is None: raise libvirtError ('virNetworkGetBridgeName() failed', net=self)
libvirtError: internal error: network 'bridged-eth0' does not have a bridge name.

"bridged-eth0" is the bridged network created on step 1.

**Comment by alinefm** [comment]
Patch sent to ML: [PATCH] Fix issue #621: Catch libvirt exception when network does not have bridge name
