### ISSUE TITLE
CentOS 6 - Unable to use logical storage

### ISSUE THREAD

**Issue by LinHub** [kimchi-project/kimchi#629]
Volume group "vmpool" not found
  Skipping volume group vmpool
 returned from cmd: vgdisplay vmpool
rc: 5 error: File descriptor 3 (/var/log/kimchi/kimchi-access.log) leaked on vgdisplay invocation. Parent PID 15480: python2
File descriptor 4 (/var/log/kimchi/kimchi-error.log) leaked on vgdisplay invocation. Parent PID 15480: python2
File descriptor 5 (/var/log/kimchi/kimchi-access.log) leaked on vgdisplay invocation. Parent PID 15480: python2
File descriptor 6 (/var/log/kimchi/kimchi-error.log) leaked on vgdisplay invocation. Parent PID 15480: python2
File descriptor 8 (socket:[22473]) leaked on vgdisplay invocation. Parent PID 15480: python2
File descriptor 14 (socket:[22485]) leaked on vgdisplay invocation. Parent PID 15480: python2
File descriptor 15 (/var/log/yum.log) leaked on vgdisplay invocation. Parent PID 15480: python2
  Volume group "vmpool" not found
  Skipping volume group vmpool
 returned from cmd: vgdisplay vmpool
[30/Mar/2015:03:05:39] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.6/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.6/site-packages/kimchi/control/base.py", line 330, in index
    return self.create(parse_request(), *args)
  File "/usr/lib/python2.6/site-packages/kimchi/control/storagepools.py", line 49, in create
    name = create(*args)
  File "/usr/lib/python2.6/site-packages/kimchi/model/storagepools.py", line 106, in create
    xml = poolDef.xml.encode("utf-8")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)

[30/Mar/2015:03:05:39] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.6/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.6/site-packages/kimchi/control/base.py", line 330, in index
    return self.create(parse_request(), *args)
  File "/usr/lib/python2.6/site-packages/kimchi/control/storagepools.py", line 49, in create
    name = create(*args)
  File "/usr/lib/python2.6/site-packages/kimchi/model/storagepools.py", line 106, in create
    xml = poolDef.xml.encode("utf-8")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)

CentOS 6 with EPEL enabled and the required RPMs installed.

I have tried to resolve it by recreating the volume, but it does not work.

pvscan
  PV /dev/sda5         lvm2 [1.73 TiB]
  Total: 1 [1.73 TiB] / in use: 0 [0   ] / in no VG: 1 [1.73 TiB]

If I create the volume group for it, the software refuses to display anything blocking further use of the software. It is a catch 22.

**Comment by ramonmedeiros** [comment]
What was the name of the storagepool? It contains special symbols?

**Comment by LinHub** [comment]
It was named vmpool.
