### ISSUE TITLE
test_repository_update  (test_model.ModelTests) fails with F20 x86_64 and ppc64 powerkvm

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/kimchi#630]
The same error occur in both scenarios:

======================================================================
ERROR: test_repository_update (test_model.ModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_model.py", line 1236, in test_repository_update
    repo_id, tmp_repo)
  File "/usr/lib64/python2.7/unittest/case.py", line 513, in assertRaises
    callableObj(*args, **kwargs)
  File "/home/danielhb/kimchi/kimchi-upstream/src/kimchi/model/host.py", line 453, in update
    return self._repositories.updateRepository(repo_id, params)
  File "/home/danielhb/kimchi/kimchi-upstream/src/kimchi/repositories.py", line 98, in updateRepository
    return self._pkg_mnger.updateRepo(repo_id, params)
  File "/home/danielhb/kimchi/kimchi-upstream/src/kimchi/repositories.py", line 281, in updateRepo
    if len(mirrorlist.strip()) == 0:
AttributeError: 'NoneType' object has no attribute 'strip'

I am taking a look at it to see if this is indeed a bug or it is an configuration issue.

**Comment by danielhb** [comment]
A patch was sent to Kimchi ML:

"[PATCH] Github issue #630: fixing None.strip() error"

**Comment by cd1** [comment]
I've already sent a [patch](http://lists.ovirt.org/pipermail/kimchi-devel/2015-March/010112.html) fixing this issue. It should be pushed soon.

**Comment by cd1** [comment]
Fixed by 1c716c6.
