### ISSUE TITLE
Test "test_vlan_tag_bridge" fails

### ISSUE THREAD

**Issue by cd1** [kimchi-project/kimchi#656]
The function `test_vlan_tag_bridge` fails when running `sudo make check` or when running it directly.

I'm using Fedora 22, Kimchi 392feb9.

## How to reproduce ##

1. Install Kimchi.
2. Go to the directory `tests`.
3. Type the following command:

```
$ sudo ./run_tests.sh test_mock_network.MockNetworkTests.test_vlan_tag_bridge
```

## Actual behavior ##

After step (3), the following error output is displayed:

```
[...]
[10/Jun/2015:15:24:52] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/kimchi/kimchi/src/kimchi/control/base.py", line 330, in index
    return self.create(parse_request(), *args)
  File "/home/kimchi/kimchi/src/kimchi/control/base.py", line 267, in create
    return res.get()
  File "/home/kimchi/kimchi/src/kimchi/control/base.py", line 215, in get
    self.lookup()
  File "/home/kimchi/kimchi/src/kimchi/control/base.py", line 140, in lookup
    self.info = lookup(*self.model_args)
  File "/home/kimchi/kimchi/src/kimchi/model/networks.py", line 263, in lookup
    'vms': self._get_vms_attach_to_a_network(name),
  File "/home/kimchi/kimchi/src/kimchi/model/networks.py", line 295, in _get_vms_attach_to_a_network
    for dom in conn.listAllDomains(0):
  File "/home/kimchi/kimchi/src/kimchi/model/libvirtconnection.py", line 66, in wrapper
    ret = f(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 4831, in listAllDomains
    for domptr in ret:
IOError: [Errno 19] No such device
127.0.0.1 - - [10/Jun/2015:15:24:52] "POST /networks HTTP/1.0" 500 1612 "" ""
[...]
======================================================================
FAIL: test_vlan_tag_bridge (test_mock_network.MockNetworkTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_mock_network.py", line 71, in test_vlan_tag_bridge
    'interface': iface, 'vlan_id': 987})
  File "test_model_network.py", line 69, in _do_network_test
    self.assertEquals(201, resp.status)
AssertionError: 201 != 500

----------------------------------------------------------------------
```

## Expected behavior ##

After step (3), the test function should complete successfully.

**Comment by ramonmedeiros** [comment]
Did you disable NetworkManager before running the test?

**Comment by ramonmedeiros** [comment]
I ran a test in a RHEL 7.1 disabling NetworkManager and did not found the error.:

```
................
======================================================================
ERROR: test_delete_running_vm (test_model.ModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_model.py", line 833, in test_delete_running_vm
    inst.vm_start(u'kīмсhī-∨м')
  File "/root/KIMCHI/src/kimchi/model/vms.py", line 1109, in start
    {'name': name, 'err': e.get_error_message()})
OperationFailed: KCHVM0019E: Unable to start virtual machine k\u012b\u043c\u0441h\u012b-\u2228\u043c. Details: error from service: CreateMachine: Invalid argument

======================================================================
FAIL: test_async_tasks (test_model.ModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_model.py", line 792, in test_async_tasks
    self.assertEquals(1, taskid)
AssertionError: 1 != 5

======================================================================
FAIL: test_debug_reports (test_model.ModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_model.py", line 967, in test_debug_reports
    "It is not necessary an error.  "
AssertionError: It is not necessary an error.  You may need to increase the timeout number by TEST_REPORT_TIMEOUT=200 ./run_tests.sh test_model

----------------------------------------------------------------------
Ran 143 tests in 526.970s
```

**Comment by alinefm** [comment]
All tests cases are passing on Fedora 23.
I will close this issue.
