### ISSUE TITLE
having glusterfs pool in libvirt causes storage tab to break

### ISSUE THREAD

**Issue by jonbayer** [kimchi-project/kimchi#672]
Hi,

I recently added a glusterFS pool to my virtualization server for migration/redundancy purposes. Unfortunately this seems to have broken the storage pane for kimchid. Here's what I get in the logs upon trying to load the storage page:

[30/Jun/2015:02:35:34] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/kimchi/control/base.py", line 328, in index
    return self.get(filter_params)
  File "/usr/lib/python2.7/site-packages/kimchi/control/base.py", line 315, in get
    resources = self._get_resources(flag_filter)
  File "/usr/lib/python2.7/site-packages/kimchi/control/storagepools.py", line 63, in _get_resources
    res_list = super(StoragePools, self)._get_resources(filter_params)
  File "/usr/lib/python2.7/site-packages/kimchi/control/base.py", line 278, in _get_resources
    res.lookup()
  File "/usr/lib/python2.7/site-packages/kimchi/control/base.py", line 140, in lookup
    self.info = lookup(*self.model_args)
  File "/usr/lib/python2.7/site-packages/kimchi/model/storagepools.py", line 321, in lookup
    path = xpath_get_text(xml, "/pool/target/path")[0]
IndexError: list index out of range

[30/Jun/2015:02:35:34] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/kimchi/control/base.py", line 328, in index
    return self.get(filter_params)
  File "/usr/lib/python2.7/site-packages/kimchi/control/base.py", line 315, in get
    resources = self._get_resources(flag_filter)
  File "/usr/lib/python2.7/site-packages/kimchi/control/storagepools.py", line 63, in _get_resources
    res_list = super(StoragePools, self)._get_resources(filter_params)
  File "/usr/lib/python2.7/site-packages/kimchi/control/base.py", line 278, in _get_resources
    res.lookup()
  File "/usr/lib/python2.7/site-packages/kimchi/control/base.py", line 140, in lookup
    self.info = lookup(*self.model_args)
  File "/usr/lib/python2.7/site-packages/kimchi/model/storagepools.py", line 321, in lookup
    path = xpath_get_text(xml, "/pool/target/path")[0]
IndexError: list index out of range

. I realize glusterFS support might not be very high on your list of priorities (so nice though). But is it possible to patch this so at least kimchi can work with my other storage pools even with glusterfs enabled?

**Comment by ramonmedeiros** [comment]
Hi Jon,

can you describe how your glusterfs storage is mounted and how you tried to add to kimchi?

Thanks.

**Comment by jonbayer** [comment]
Hi Ramon,

Gluster storage is mounted by adding a storage pool to libvirt. Just added
directly to libvirt, did not add to kimchi at all. Now when I check the
storage tab of kimchi it just errors out.
