### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by jaredallard** [kimchi-project/kimchi#692]
System: `arch`
Linux: `4.0.7`
Arch: `amd64`

I *should* have all the dependencies.

Build Line: `./autogen.sh --prefix=/usr --sysconfdir=/etc --localstatedir=/var PYTHON=/usr/bin/python2`

```
[root@celestia kimchi]# kimchid --host=0.0.0.0
Traceback (most recent call last):
  File "/usr/bin/kimchid", line 99, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/kimchid", line 96, in main
    kimchi.server.main(options)
  File "/usr/lib/python2.7/site-packages/kimchi/server.py", line 187, in main
    srv = Server(options)
  File "/usr/lib/python2.7/site-packages/kimchi/server.py", line 62, in __init__
    start_proxy(options)
  File "/usr/lib/python2.7/site-packages/kimchi/proxy.py", line 99, in start_proxy
    subprocess.call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by laggarcia** [comment]
File "/usr/lib/python2.7/site-packages/kimchi/proxy.py", line 99, in start_proxy
    subprocess.call(cmd)

This is trying to start nginx. Do you have nginx installed and reachable on the PATH?

**Comment by jaredallard** [comment]
Hm, I don't that'd make sense.

**Comment by ramonmedeiros** [comment]
Seems that the user www-data is not present in the system. Please, create the user and try again.

**Comment by jaredallard** [comment]
@ramonmedeiros That would be it! Thanks!!
