### ISSUE TITLE
gingerbase: objectstore issues with new project clone

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/kimchi#744]
I came very close to create a tag 'Annoying' just to put in this bug.

Wok+kimchi+gingerbase don't run after a fresh clone. Here's the steps I've taken:

- fresh clone repo
- cd to src/wok/plugins/gingerbase
- ./autogen.sh --system && make
- cd to src/wok/plugins/kimchi
- ./autogen.sh --system && make
- cd to wok/project root
- ./autogen.sh --system && make

Then trying to run wokd:

$ sudo src/wokd --environment=dev
Plugin configuration file /home/danielhb/kimchi-master/kimchi/src/wok/plugins/ginger/ginger.conf doesn't exist.
Plugin configuration file /home/danielhb/kimchi-master/kimchi/src/wok/plugins/ginger/ginger.conf doesn't exist.
Failed to import plugin plugins.kimchi.KimchiRoot
Traceback (most recent call last):
  File "src/wokd", line 101, in <module>
    sys.exit(main(sys.argv[1:]))
  File "src/wokd", line 98, in main
    wok.server.main(options)
  File "/home/danielhb/kimchi-master/kimchi/src/wok/server.py", line 205, in main
    srv = Server(options)
  File "/home/danielhb/kimchi-master/kimchi/src/wok/server.py", line 137, in __init__
    self._load_plugins(options)
  File "/home/danielhb/kimchi-master/kimchi/src/wok/server.py", line 160, in _load_plugins
    plugin_app = import_class(plugin_class)(options)
  File "/home/danielhb/kimchi-master/kimchi/src/wok/plugins/gingerbase/gingerbase.py", line 37, in __init__
    self.model = gingerBaseModel.Model()
  File "/home/danielhb/kimchi-master/kimchi/src/wok/plugins/gingerbase/model/model.py", line 46, in __init__
    self.objstore = ObjectStore(objstore_loc)
  File "/home/danielhb/kimchi-master/kimchi/src/wok/objectstore.py", line 91, in __init__
    self._init_db()
  File "/home/danielhb/kimchi-master/kimchi/src/wok/objectstore.py", line 94, in _init_db
    conn = self._get_conn()
  File "/home/danielhb/kimchi-master/kimchi/src/wok/objectstore.py", line 117, in _get_conn
    timeout=10)
sqlite3.OperationalError: unable to open database file

This error can be fixed by creating the 'data' subdir in kimchi and gingerbase dirs and then creating a file named 'objectstore' and trying to redo the building steps in wok. I've managed to fix it once in a Fedora22 but, when trying to clone the project again in an Ubuntu 15 VM, I'm stuck.

**Comment by danielhb** [comment]
Resetting the tree to the pre-gingerbase status ( commit 570719e7aed0265e949cf3d9b6d049700938102d )  will make wok launch:

$ sudo src/wokd --environment=dev
Plugin configuration file /home/danielhb/kimchi-reset/kimchi/src/wok/plugins/ginger/ginger.conf doesn't exist.
Plugin configuration file /home/danielhb/kimchi-reset/kimchi/src/wok/plugins/ginger/ginger.conf doesn't exist.
Failed to import plugin plugins.kimchi.KimchiRoot
[27/Oct/2015:21:40:58] ENGINE Listening for SIGHUP.
[27/Oct/2015:21:40:58] ENGINE Listening for SIGTERM.
[27/Oct/2015:21:40:58] ENGINE Listening for SIGUSR1.
[27/Oct/2015:21:40:58] ENGINE Bus STARTING
[27/Oct/2015:21:40:58] ENGINE Started monitor thread 'Autoreloader'.
[27/Oct/2015:21:40:58] ENGINE Serving on http://127.0.0.1:8010
[27/Oct/2015:21:40:58] ENGINE Bus STARTED

I'll ignore the  'Failed to import plugin plugins.kimchi.KimchiRoot' for now (perhaps we can create a bug for this type of message later) as it is probably a missing dependency. Thing is that, as far as I can tell, the problem appeared after the introduction of gingerbase and any other patch that followed it.

**Comment by chandrureddy** [comment]
Daniel quick suggestion:
Please try running both autogen and make commands using sudo and see if this could change.

**Comment by danielhb** [comment]
@chandrureddy  I've tried that and unfortunately the bug persisted:

$ sudo src/wokd --environment=dev
Failed to import plugin plugins.ginger.Ginger
Failed to import plugin plugins.kimchi.KimchiRoot
Traceback (most recent call last):
  File "src/wokd", line 101, in <module>
    sys.exit(main(sys.argv[1:]))
  File "src/wokd", line 98, in main
    wok.server.main(options)
  File "/home/danielhb/kimchi/src/wok/server.py", line 205, in main
    srv = Server(options)
  File "/home/danielhb/kimchi/src/wok/server.py", line 137, in __init__
    self._load_plugins(options)
  File "/home/danielhb/kimchi/src/wok/server.py", line 160, in _load_plugins
    plugin_app = import_class(plugin_class)(options)
  File "/home/danielhb/kimchi/src/wok/plugins/gingerbase/gingerbase.py", line 37, in __init__
    self.model = gingerBaseModel.Model()
  File "/home/danielhb/kimchi/src/wok/plugins/gingerbase/model/model.py", line 46, in __init__
    self.objstore = ObjectStore(objstore_loc)
  File "/home/danielhb/kimchi/src/wok/objectstore.py", line 91, in __init__
    self._init_db()
  File "/home/danielhb/kimchi/src/wok/objectstore.py", line 94, in _init_db
    conn = self._get_conn()
  File "/home/danielhb/kimchi/src/wok/objectstore.py", line 117, in _get_conn
    timeout=10)
sqlite3.OperationalError: unable to open database file


I'll try to look deeper into this issue when I have the chance

**Comment by chandrureddy** [comment]
Hi Daniel, 
I guess I know the problem here.  
Basically one the following directory structure is missing during the plug in installation.
/var/lib/kimchi

I would like to send a mail for the opinion on the directory structure and will fix the issue.
