### ISSUE TITLE
VMs created within Kimchi cannot be started - Error KCHVM0019E

### ISSUE THREAD

**Issue by mobibaud** [kimchi-project/kimchi#801]
Just trying kimchi and went through the install with no problems. 

Kimchi/wok/gingerbase are installed properly and correctly shows list of vms/templates etc. 

I created a template (debian 8) and created a VM within kimchi. When I attempt to start it I'm met with the following error:

KCHVM0019E: Unable to start virtual machine git. Details: unsupported configuration: memory hotplug isn't supported by this QEMU binary

Loading up virtual-manager this is the full error report from it:

Error starting domain: unsupported configuration: memory hotplug isn't supported by this QEMU binary

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 96, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 117, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/domain.py", line 1162, in startup
    self._backend.create()
  File "/usr/lib/python2.7/dist-packages/libvirt.py", line 866, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirtError: unsupported configuration: memory hotplug isn't supported by this QEMU binary

Seems all of this is tied into the use of   ...memory unit='KiB'>524288</memory...
in the VM setup which is not present on the VM created via virtual-manager. 

[vm_in_error.xml.zip](https://github.com/kimchi-project/kimchi/files/72843/vm_in_error.xml.zip)

Removing the line from the xml, changing the name/uuid and virsh allows me to create the VM without any issues. 

Using virsh 1.2.17.
And kimchi 2.0.0-0

**Comment by mobibaud** [comment]
Re-visiting this again, this may be the qemu-kvm version (1.5.3) that does not support hotplug memory (that's kind of what the error was alluding to in the first place). 

Since I'm mostly just building an old-ish computer for a VM lab, i'll rebuild with Fedora Server instead and  get kimchi installed - will ping back here to confirm if this is working fine using a newer qemu-kvm version.

**Comment by mobibaud** [comment]
And final comment - yes - everything is working fine using qemu 2.4.1 (in Fedora Core 23). 

I guess this should be more viewed as a change request for the install doc as this qemu requirement is not listed (or I'm blind).
