### ISSUE TITLE
Virtual network creation does not work on openSUSE Leap 42.1

### ISSUE THREAD

**Issue by lcorreia** [kimchi-project/kimchi#811]
Got the error below trying to create a virtual network either using Linux bridge or OVS bridge.
It seems an unhandled issue is causing self.info to be empty.

[31/Dec/2015:15:34:40] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 353, in index
    return self.create(parse_request(), *args)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 290, in create
    return res.get()
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 221, in get
    return wok.template.render(get_class_name(self), self.data)
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/control/networks.py", line 46, in data
    'vms': self.info['vms'],
KeyError: 'vms'

**Comment by lcorreia** [comment]
For a NAT virtual network, I got this error in the log:

[04/Jan/2016:14:21:06] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 353, in index
    return self.create(parse_request(), *args)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 285, in create
    name = create(*args)
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/model/networks.py", line 95, in create
    self._set_network_subnet(params)
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/model/networks.py", line 132, in _set_network_subnet
    netaddr = self._get_available_address()
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/model/networks.py", line 126, in _get_available_address
    return knetwork.get_one_free_network(invalid_addrs, addr_pools)
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/network.py", line 62, in get_one_free_network
    used_nets = used_nets + get_dev_netaddrs()
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/network.py", line 48, in get_dev_netaddrs
    devnet = get_dev_netaddr(dev)
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/network.py", line 40, in get_dev_netaddr
    info = ethtool.get_interfaces_info(dev)[0]
AttributeError: 'module' object has no attribute 'get_interfaces_info'

**Comment by lcorreia** [comment]
All those errors were caused by an old python-ethtool. We can close this.
