### ISSUE TITLE
Cannot run kimchi on ubuntu 15.10: libvirtError('invalid argument: could not find capabilities for arch=x86_64 domaintype=kvm ',)

### ISSUE THREAD

**Issue by ramonmedeiros** [kimchi-project/kimchi#813]
How to reproduce:

install fresh ubuntu 15.10
Try to run wok+kimchi

you'll see some errors about capabilities

libvirt:  error : internal error: Child process (/sbin/showmount --no-headers --exports localhost) unexpected exit status 1: clnt_create: RPC: Program not registered
internal error: Child process (/sbin/showmount --no-headers --exports localhost) unexpected exit status 1: clnt_create: RPC: Program not registered

libvirt: Capabilities Utils error : invalid argument: could not find capabilities for arch=x86_64 domaintype=kvm 
[04/Jan/2016:13:21:43] ENGINE Error in 'start' listener <bound method CapabilitiesModel._set_capabilities of <wok.plugins.kimchi.model.config.CapabilitiesModel object at 0x7f23d0973c50>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/process/wspbus.py", line 205, in publish
    output.append(listener(*args, **kwargs))
  File "/root/WOK/src/wok/plugins/kimchi/model/config.py", line 93, in _set_capabilities
    self.mem_hotplug_support = FeatureTests.has_mem_hotplug_support(conn)
  File "/root/WOK/src/wok/plugins/kimchi/model/featuretests.py", line 228, in has_mem_hotplug_support
    'arch': arch})
  File "/root/WOK/src/wok/plugins/kimchi/model/libvirtconnection.py", line 65, in wrapper
    ret = f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/libvirt.py", line 3541, in defineXML
    if ret is None:raise libvirtError('virDomainDefineXML() failed', conn=self)
libvirtError: invalid argument: could not find capabilities for arch=x86_64 domaintype=kvm 

*** Running feature tests ***
*** Feature tests completed ***
[04/Jan/2016:13:21:43] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/process/wspbus.py", line 243, in start
    self.publish('start')
  File "/usr/lib/python2.7/dist-packages/cherrypy/process/wspbus.py", line 223, in publish
    raise exc
ChannelFailures: libvirtError('invalid argument: could not find capabilities for arch=x86_64 domaintype=kvm ',)

**Comment by ramonmedeiros** [comment]
I'm taking a look

**Comment by ramonmedeiros** [comment]
Hi,

the problem was nested virtualization support. To add it, follow this instructions:

http://kashyapc.com/2012/01/14/nested-virtualization-with-kvm-intel/

**Comment by pvital** [comment]
Looks like enable the kvm_intel (or kvm_amd) options in host's boot is not enough. I had to set up the VM to use the same CPU model of host:

```
$ sudo virsh edit <domain>
  <cpu mode='host-model'>
```

**Comment by yvv47** [comment]
I am also getting the same error, I have that VM build on VMware ESXi.
