### ISSUE TITLE
Backend should tell the frontend when a PCI device is no longer attached

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/kimchi#817]
I tried to hot-plug and hot-unplug a PCI device. It worked fine but, for some reason, the UI was not updated accordingly. So, if I click on the device to unplug it again I get an error:

![image](https://cloud.githubusercontent.com/assets/670087/12150225/b79a208a-b48f-11e5-9b31-2a741ecefbfe.png)

And the backend throws an error because I tried to detach a device no longer attached:
```
[06/Jan/2016:12:04:27] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/root/zvn/fork_daniel/wok/src/wok/control/base.py", line 176, in index
    'PUT': self.update}[method](*args, **kargs)
  File "/root/zvn/fork_daniel/wok/src/wok/control/base.py", line 153, in delete
    fn(*self.model_args)
  File "/root/zvn/fork_daniel/wok/src/wok/plugins/kimchi/model/vmhostdevs.py", line 306, in delete
    xmlstr, get_vm_config_flag(dom, mode='all'))
  File "/root/zvn/fork_daniel/wok/src/wok/plugins/kimchi/model/libvirtconnection.py", line 65, in wrapper
    ret = f(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 1094, in detachDeviceFlags
    if ret == -1: raise libvirtError ('virDomainDetachDeviceFlags() failed', dom=self)
libvirtError: invalid argument: device not present in domain configuration
```

I think, in this case, the backend should handle this error and return something to the frontend that explains that such device was already removed, so the frontend has another opportunity to update itself.

**Comment by pvital** [comment]
Sometime ago I got a possible usability issue during PCI passthrough due to the return time of attach and de-attach a device provided by backend and the reflection this causes in UI.

Looks like there're some differente ways provided by libvirt and QEMU to check if the hot plug/unplug operation run to completion.

Please, assign this issue to me.
