### ISSUE TITLE
remote iso image not display

### ISSUE THREAD

**Issue by minoru9999** [kimchi-project/kimchi#840]
Kimchi 2.0 on CentOS7(1511) and Fedora23.

Add Template With Remote ISO Image.
But Not Show Any ISO Image.
wok-error.log have a Error

```
HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 351, in index
    return self.get(filter_params)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 338, in get
    resources = self._get_resources(flag_filter)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 295, in _get_resources
    idents = get_list(*self.model_args, **flag_filter)
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/model/config.py", line 137, in get_list
    pool = ThreadPool(processes=n_processes)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 727, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 152, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
```

Why Number Processed least 1??

**Comment by minoru9999** [comment]
Problem was solved.

Kimchi's distros.d path is differ
```bash
mv /etc/wok/plugins.d/distros.d /etc/wok/plugins.d/distros.d.deleteme
ln -s /etc/kimchi/distros.d /etc/wok/plugins.d/distors.d
```
Kimchi's distros.d is /etc/kimchi/distros.d
But config.py called distros.d is /etc/wok/plugins.d/distros.d


Kimchi's config.py is set PluginPaths('kimchi').conf_dir, 'distros.d'
And
Wok,PluginPaths is set /etc/wok/plugins.d, not /etc/kimch

Thanks.

**Comment by Truja** [comment]
Patch sent to ustream
