### ISSUE TITLE
Error display Guests

### ISSUE THREAD

**Issue by behigh** [kimchi-project/kimchi#848]
Guests are not displayed. In the log, I found these errors
`HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 351, in index
    return self.get(filter_params)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 338, in get
    resources = self._get_resources(flag_filter)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 301, in _get_resources
    res.lookup()
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 146, in lookup
    self.info = lookup(*self.model_args)
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/model/vms.py", line 1140, in lookup
    screenshot = self.vmscreenshot.lookup(name)
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/model/vms.py", line 1793, in lookup
    screenshot = self.get_screenshot(vm_uuid, self.objstore, self.conn)
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/model/vms.py", line 1824, in get_screenshot
    return LibvirtVMScreenshot(params, conn)
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/model/vms.py", line 1829, in __init__
    VMScreenshot.__init__(self, vm_uuid)
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/screenshot.py", line 50, in __init__
    self.vm_uuid = args['uuid']
KeyError: 'uuid'`

**Comment by alinefm** [comment]
Hi @behigh !

Could you provide more details on how to reproduce this behavior?
OS? Wok, Kimchi version? How did you create the virtual machine? Using Kimchi or other tool?

**Comment by joshuaswarren** [comment]
I'm having the same issue, with the exact same stack trace. 

I'm not sure about @behigh, but in my case, the info you asked for @alinefm is:

OS: Centos 7
Wok version: I'm not sure? It looks like there's no wokd --version command and running wokd doesn't show the version.
Kimchi version: 2.0.0-0

The virtual machines were created under Kimchi, but it was under Kimchi v1. The VMs are definitely still there, and they're running, per "virsh list --all" on the command line. I'm guessing the problem lies in the fact that they were created in Kimchi v1 and I upgraded to Kimchi v2 very early on? I'm still hopeful there's a way to get them added back into Kimchi v2 correctly.

**Comment by joshuaswarren** [comment]
FYI, after reading issue 792, I temporarily moved /var/lib/kimchi/objectstore so that Kimchi recreated the file. Oddly enough, the "The server encountered an unexpected condition which prevented it from fulfilling the request." error still appears but Guests are now listed correctly on the Guests page, so it seems like this might be a similar upgrade-related objectstore problem?

**Comment by behigh** [comment]
Hi, @alinefm 
Os Centos 7
Kimchi: 2.0.0 installed from rpm
VMs created under Kimchi v1
The situation is similar to @joshuaswarren

**Comment by behigh** [comment]
Upgraded to version 2.1 - same error
After deleting `/var/lib/kimchi/objectstore` and restart wok all earned.
