### ISSUE TITLE
HTTP 500 error in interfaces tab for all virtual hosts

### ISSUE THREAD

**Issue by ioben** [kimchi-project/kimchi#849]
When visiting the interface panel for any of my virtual machines I get the following error from the wokd error log:
```
[01/Mar/2016:06:10:41] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 351, in index
    return self.get(filter_params)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 338, in get
    resources = self._get_resources(flag_filter)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 301, in _get_resources
    res.lookup()
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 146, in lookup
    self.info = lookup(*self.model_args)
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/model/vmifaces.py", line 145, in lookup
    info['ips'] = self._get_ips(vm, info['mac'], info['network'])
KeyError: 'network'
```

I was able to fix the issue by modifying `/usr/lib/python2.7/site-packages/wok/plugins/kimchi/model/vmifaces.py`:
```
info['ips'] = self._get_ips(vm, info['mac'], info['network'])
```

to:
```
if 'network' in info:
    info['ips'] = self._get_ips(vm, info['mac'], info['network'])
```

Not sure if that's an optimal solution though.

Versions
```
Compiled against library: libvirt 1.2.17
Using library: libvirt 1.2.17
Using API: QEMU 1.2.17
Running hypervisor: QEMU 2.3.0
```

**Comment by alinefm** [comment]
Hi @ioben!

Thanks for reporting the problem. I am working on a patch to fix it.
