### ISSUE TITLE
Kimchi problem

### ISSUE THREAD

**Issue by jadibou** [kimchi-project/kimchi#852]
Hello,

i install kimchi on my fedora serveur
and dont have a virtual machine tools ..
look my panel, i dont have a guest, template, storage menu ...

![capture](https://cloud.githubusercontent.com/assets/17614596/13492384/fee03c70-e137-11e5-9fd8-e912c8ca859f.JPG)

do you have a solution for me ? 

tkt

**Comment by alinefm** [comment]
Hi @jadibou !

Seems Kimchi is not up!
What you are seeing is wok + gingerbase.
How did you install wok and gingerbase? Have you installed Kimchi as well?

**Comment by jadibou** [comment]
I have install wok and gingerbase :
 yum install wok.rpm
yum install gingerbase.rpm
yum install kimchi.rpm 

i dolwnload the rpm in this page : http://kimchi-project.github.io/gingerbase/

i use fedora

**Comment by jadibou** [comment]
kimchid.service - Kimchi server
   Loaded: loaded (/usr/lib/systemd/system/kimchid.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since jeu. 2016-03-03 15:35:46 CET; 2min 30s ago
  Process: 1405 ExecStop=/bin/kill -TERM $MAINPID (code=exited, status=1/FAILURE)
  Process: 1156 ExecStart=/usr/bin/kimchid (code=exited, status=1/FAILURE)
 Main PID: 1156 (code=exited, status=1/FAILURE)

mars 03 15:35:46 localhost.localdomain kimchid[1156]: File "/usr/lib/python2....
mars 03 15:35:46 localhost.localdomain kimchid[1156]: self.host_info = self._...
mars 03 15:35:46 localhost.localdomain kimchid[1156]: File "/usr/lib/python2....
mars 03 15:35:46 localhost.localdomain kimchid[1156]: res['cpus'] = psutil.NU...
mars 03 15:35:46 localhost.localdomain kimchid[1156]: AttributeError: 'module...
mars 03 15:35:46 localhost.localdomain systemd[1]: kimchid.service: Main proc...
mars 03 15:35:46 localhost.localdomain kill[1405]: kill: pas assez d'arguments
mars 03 15:35:46 localhost.localdomain systemd[1]: kimchid.service: Control p...
mars 03 15:35:46 localhost.localdomain systemd[1]: kimchid.service: Unit ente...
mars 03 15:35:46 localhost.localdomain systemd[1]: kimchid.service: Failed wi...
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by jadibou** [comment]
kimchid.service - Kimchi server
   Loaded: loaded (/usr/lib/systemd/system/kimchid.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since jeu. 2016-03-03 15:35:46 CET; 3min 0s ago
  Process: 1405 ExecStop=/bin/kill -TERM $MAINPID (code=exited, status=1/FAILURE)
  Process: 1156 ExecStart=/usr/bin/kimchid (code=exited, status=1/FAILURE)
 Main PID: 1156 (code=exited, status=1/FAILURE)

mars 03 15:35:46 localhost.localdomain kimchid[1156]: File "/usr/lib/python2.7/site-packages/kimchi/model/host.py", line 52, in __init__
mars 03 15:35:46 localhost.localdomain kimchid[1156]: self.host_info = self._get_host_info()
mars 03 15:35:46 localhost.localdomain kimchid[1156]: File "/usr/lib/python2.7/site-packages/kimchi/model/host.py", line 90, in _get_host_info
mars 03 15:35:46 localhost.localdomain kimchid[1156]: res['cpus'] = psutil.NUM_CPUS
mars 03 15:35:46 localhost.localdomain kimchid[1156]: AttributeError: 'module' object has no attribute 'NUM_CPUS'
mars 03 15:35:46 localhost.localdomain systemd[1]: kimchid.service: Main process exited, code=exited, status=1/FAILURE
mars 03 15:35:46 localhost.localdomain kill[1405]: kill: pas assez d'arguments
mars 03 15:35:46 localhost.localdomain systemd[1]: kimchid.service: Control process exited, code=exited status=1
mars 03 15:35:46 localhost.localdomain systemd[1]: kimchid.service: Unit entered failed state.
mars 03 15:35:46 localhost.localdomain systemd[1]: kimchid.service: Failed with result 'exit-code'.

**Comment by alinefm** [comment]
Is psutil package installed?
Which Fedora version are you running? Fedora 23?

**Comment by jadibou** [comment]
yes fedora 23

**Comment by alinefm** [comment]
Please, stop wokd service and run it manually:
`sudo wokd --environment=development`
And paste here the command output

**Comment by jadibou** [comment]
[root@localhost ~]#  wokd --environment=development
nginx: [emerg] bind() to 0.0.0.0:8001 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8001 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8001 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8001 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8001 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
nginx: [emerg] still could not bind()
Loading YumUpdate features.
rc: 1 error: Cannot talk to Tuned daemon via DBus. Is Tuned daemon running?
 returned from cmd: tuned-adm active
rc: 1 error: Cannot talk to Tuned daemon via DBus. Is Tuned daemon running?
 returned from cmd: tuned-adm active
[03/Mar/2016:20:39:45] ENGINE Listening for SIGHUP.
[03/Mar/2016:20:39:45] ENGINE Listening for SIGTERM.
[03/Mar/2016:20:39:45] ENGINE Listening for SIGUSR1.
[03/Mar/2016:20:39:45] ENGINE Bus STARTING
[03/Mar/2016:20:39:45] ENGINE Started monitor thread 'Autoreloader'.
[03/Mar/2016:20:39:50] ENGINE Error in 'start' listener <bound method Server.sta                                               rt of <cherrypy._cpserver.Server object at 0x7efc59ca8790>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 205,                                                in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpserver.py", line 168, in st                                               art
    ServerAdapter.start(self)
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 170,                                                in start
    wait_for_free_port(*self.bind_addr)
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 438,                                                in wait_for_free_port
    raise IOError("Port %r not free on %r" % (port, host))
IOError: Port 8010 not free on '127.0.0.1'

*** Running feature tests ***
*** Feature tests completed ***
[03/Mar/2016:20:39:50] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 243,                                                in start
    self.publish('start')
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 223,                                                in publish
    raise exc
ChannelFailures: IOError("Port 8010 not free on '127.0.0.1'",)

[03/Mar/2016:20:39:50] ENGINE Bus STOPPING
[03/Mar/2016:20:39:50] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer((                                               '127.0.0.1', 8010)) already shut down
[03/Mar/2016:20:39:50] ENGINE Stopped thread 'Autoreloader'.
[03/Mar/2016:20:39:50] ENGINE Bus STOPPED
[03/Mar/2016:20:39:50] ENGINE Bus EXITING
[03/Mar/2016:20:39:50] ENGINE Bus EXITED

**Comment by alinefm** [comment]
Hi @jadibou!

Seems wokd was already running when you tried to run it manually.
Please, do:

`service wokd stop`

and then:

`wokd --environment=development`

And paste the command output again.

**Comment by jadibou** [comment]
[root@localhost ~]# wokd --environment=development
Loading YumUpdate features.
rc: 1 error: Cannot talk to Tuned daemon via DBus. Is Tuned daemon running?
 returned from cmd: tuned-adm active
rc: 1 error: Cannot talk to Tuned daemon via DBus. Is Tuned daemon running?
 returned from cmd: tuned-adm active
[08/Mar/2016:14:38:13] ENGINE Listening for SIGHUP.
[08/Mar/2016:14:38:13] ENGINE Listening for SIGTERM.
[08/Mar/2016:14:38:13] ENGINE Listening for SIGUSR1.
[08/Mar/2016:14:38:13] ENGINE Bus STARTING
[08/Mar/2016:14:38:13] ENGINE Started monitor thread 'Autoreloader'.
[08/Mar/2016:14:38:13] ENGINE Serving on http://127.0.0.1:8010
*** Running feature tests ***
*** Feature tests completed ***
[08/Mar/2016:14:38:13] ENGINE Bus STARTED

**Comment by alinefm** [comment]
Hrm... no error reported there
@jadibou, were you able to see the Virtualization tab yet?

With wokd running, could you run, in a different terminal the following command and paste the output:

curl -u <user:password> -H "Content-Type: application/json" -H "Accept: application/json" https://localhost:8001/plugins -k

**Comment by jadibou** [comment]
Hello

curl -u user:password -H "Content-Type: application/json" -H "Accept: application/json" https://localhost:8001/plugins -k
[
  "kimchi",
  "gingerbase",
  "ginger"

**Comment by alinefm** [comment]
Could you check on Firebug if there is any JS error?

I am not sure on what is wrong there.

**Comment by thesabbir** [comment]
Sames issue. Error log might help I suppose.
```
❯ tail -f  /var/log/wok/wok-error.log                                                                                                                                                           root@server
Failed to import plugin plugins.ginger.Ginger, error: No module named parted
Failed to import plugin plugins.kimchi.Kimchi, error: Class plugins.kimchi.Kimchi can not be imported, error: No module named parted
[26/Oct/2016:00:53:06] ENGINE Listening for SIGHUP.
[26/Oct/2016:00:53:06] ENGINE Listening for SIGTERM.
[26/Oct/2016:00:53:06] ENGINE Listening for SIGUSR1.
[26/Oct/2016:00:53:06] ENGINE Bus STARTING
[26/Oct/2016:00:53:06] ENGINE Serving on 127.0.0.1:8010
[26/Oct/2016:00:53:06] ENGINE Bus STARTED
[26/Oct/2016:00:53:18] ENGINE Started monitor thread 'Session cleanup'.
WOKAUTH0002E: You are not authorized to access Kimchi
```
CentOS 7
Kimchi, WOK, Ginger, Gingerbase from git.

**Comment by thesabbir** [comment]
Kimchi dependencies were missing. Found solution [here](https://github.com/kimchi-project/kimchi/blob/master/docs/fedora-deps.md).
