### ISSUE TITLE
template create from local image fails "unexpected condition

### ISSUE THREAD

**Issue by RmsMit** [kimchi-project/kimchi#925]
After install of kimchi 2.1 on centos7 box the GUI works OK and I log in and see the VMs (previously configured in virt-manager) however when I goto create template and select local image and enter "/var/lib/libvirt/images/Base_images/BASE_winXP.qcow2" as the file path the create process fails showing the following error on the web GUI

**The server encountered an unexpected condition which prevented it from fulfilling the request**

The /var/log/wok/wok-error.log file shows `13/Apr/2016:10:53:45] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 413, in index
    result = self.create(params, *args)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 335, in create
    name = create(*args)
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/model/templates.py", line 77, in create
    t = LibvirtVMTemplate(params, scan=True, conn=self.conn)
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/model/templates.py", line 262, in __init__
    VMTemplate.__init__(self, args, scan)
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/vmtemplate.py", line 59, in __init__
    distro, version = self._get_os_info(args, scan)
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/vmtemplate.py", line 141, in _get_os_info
    distro, version = imageinfo.probe_image(d['base'])
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/imageinfo.py", line 53, in probe_image
    g.launch()
  File "/usr/lib64/python2.7/site-packages/guestfs.py", line 4731, in launch
    r = libguestfsmod.launch (self._o)
RuntimeError: could not create appliance through libvirt.

Try running qemu directly without libvirt using this environment variable:
export LIBGUESTFS_BACKEND=direct

Original error from libvirt: Cannot access storage file '/tmp/libguestfsgo4s1j/overlay2' (as uid:107, gid:107): No such file or directory [code=38 domain=18]
`
I have assumed it is a permissions issue and have made the qcow2 image with open permisisons and disabled selinux to be sure they are not a factor. I do not see this /tmp/libguestfs* directory in /tmp

This also worked when I used fedora packages supplied by fedora on a fedora 23 host but that package was kimchi version 1.4. this is now a centos7 with kimchi 2.1 installed as per the kimchi web site instructions.

**Comment by alinefm** [comment]
It was fixed by d707a6913ec7c5b10f61502344ce1c7de1f41571
