### ISSUE TITLE
Unable to start wokd with kimchi (master branch) installed

### ISSUE THREAD

**Issue by harche** [kimchi-project/kimchi#945]
```
15:58:41-root/$ wokd 
Traceback (most recent call last):
  File "/usr/bin/wokd", line 106, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/wokd", line 103, in main
    wok.server.main(options)
  File "/usr/lib/python2.7/dist-packages/wok/server.py", line 242, in main
    srv = Server(options)
  File "/usr/lib/python2.7/dist-packages/wok/server.py", line 174, in __init__
    self._load_plugins(options)
  File "/usr/lib/python2.7/dist-packages/wok/server.py", line 195, in _load_plugins
    plugin_app = import_class(plugin_class)(options)
  File "/usr/lib/python2.7/dist-packages/wok/plugins/kimchi/root.py", line 51, in __init__
    self.model = kimchiModel.Model()
  File "/usr/lib/python2.7/dist-packages/wok/plugins/kimchi/model/model.py", line 68, in __init__
    models.append(instance(**kargs))
  File "/usr/lib/python2.7/dist-packages/wok/basemodel.py", line 54, in __call__
    inst = super(Singleton, cls).__call__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/wok/plugins/kimchi/model/config.py", line 61, in __init__
    self._set_capabilities()
  File "/usr/lib/python2.7/dist-packages/wok/plugins/kimchi/model/config.py", line 105, in _set_capabilities
    self.nfs_target_probe = FeatureTests.libvirt_support_nfs_probe(conn)
  File "/usr/lib/python2.7/dist-packages/wok/plugins/kimchi/model/featuretests.py", line 156, in libvirt_support_nfs_probe
    conn.findStoragePoolSources('netfs', _get_xml(), 0)
AttributeError: 'NoneType' object has no attribute 'findStoragePoolSources'

```

**Comment by alinefm** [comment]
I have seen this problem when libvirt service is not running and you tried to start wokd with Kimchi.
It was already fixed by 2293369000dcca176db632185a54354b4381bbbb
Please, reopen if the problem persists.
