### ISSUE TITLE
Latest Kimchi installation failed to bring up wok with error "could not find capabilities for arch=x86_64 domaintype=kvm "

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/kimchi#957]
Environment:
[root@localhost wok]# uname -a
Linux localhost.localdomain 4.4.9-300.fc23.x86_64 #1 SMP Wed May 4 23:56:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost wok]# cat /etc/system-release
Fedora release 23 (Twenty Three)
[root@localhost wok]# virsh capabilities | grep x86
      <arch>x86_64</arch>
    <arch name='x86_64'>
      <emulator>/usr/bin/qemu-system-x86_64</emulator>

[root@localhost wok]# wokd --host=0.0.0.0
WARNING: no 'numpy' module, HyBi protocol will be slower
libvirt: Capabilities Utils error : invalid argument: could not find capabilities for arch=x86_64 domaintype=kvm 
Traceback (most recent call last):
  File "/usr/bin/wokd", line 106, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/wokd", line 103, in main
    wok.server.main(options)
  File "/usr/lib/python2.7/site-packages/wok/server.py", line 242, in main
    srv = Server(options)
  File "/usr/lib/python2.7/site-packages/wok/server.py", line 174, in __init__
    self._load_plugins(options)
  File "/usr/lib/python2.7/site-packages/wok/server.py", line 195, in _load_plugins
    plugin_app = import_class(plugin_class)(options)
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/root.py", line 51, in __init__
    self.model = kimchiModel.Model()
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/model/model.py", line 71, in __init__
    models.append(instance(**kargs))
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/model/storagevolumes.py", line 553, in __init__
    self.storagevolume = StorageVolumeModel(**kargs)
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/model/storagevolumes.py", line 279, in __init__
    self.libvirt_user = UserTests().probe_user()
  File "/usr/lib/python2.7/site-packages/wok/plugins/kimchi/kvmusertests.py", line 59, in probe_user
    dom = conn.createXML(xml, flags=f)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 3611, in createXML
    if ret is None:raise libvirtError('virDomainCreateXML() failed', conn=self)
libvirt.libvirtError: invalid argument: could not find capabilities for arch=x86_64 domaintype=kvm

**Comment by rafaelsoaresbr** [comment]
Try this solution: http://kashyapc.com/2012/01/14/nested-virtualization-with-kvm-intel/
#813

**Comment by alinefm** [comment]
Closing due inactivity.

Please, reopen if nested virtualization is proper enabled on system and the problem persists.
